In [55]:
import pandas as pd
import numpy as np

anos = [2021, 2022, 2023, 2024, 2025]
dfs = []

for ano in anos:
    caminho = f"../data/raw/DRE/dfp_cia_aberta_DRE_con_{ano}.csv"
    df = pd.read_csv(caminho, sep=";", encoding="latin1")
    df["ANO_ARQUIVO"] = ano
    dfs.append(df)
    print(f"{ano}: {df.shape[0]} linhas")  # confere se algum ano veio vazio/suspeito

df_dre = pd.concat(dfs, ignore_index=True)
print("Total:", df_dre.shape)
df_dre.head()

2021: 32644 linhas
2022: 33784 linhas
2023: 33970 linhas
2024: 32776 linhas
2025: 30786 linhas
Total: (163960, 16)

,CNPJ_CIA,DT_REFER,VERSAO,DENOM_CIA,CD_CVM,GRUPO_DFP,MOEDA,ESCALA_MOEDA,ORDEM_EXERC,DT_INI_EXERC,DT_FIM_EXERC,CD_CONTA,DS_CONTA,VL_CONTA,ST_CONTA_FIXA,ANO_ARQUIVO
0,00.000.000/0001-91,2021-12-31,2,BCO BRASIL S.A.,1023,DF Consolidado - Demonstração do Resultado,REAL,MIL,PENÚLTIMO,2020-01-01,2020-12-31,3.01,Receitas de Intermediação Financeira,"98,659,704.00",S,2021
1,00.000.000/0001-91,2021-12-31,2,BCO BRASIL S.A.,1023,DF Consolidado - Demonstração do Resultado,REAL,MIL,ÚLTIMO,2021-01-01,2021-12-31,3.01,Receitas de Intermediação Financeira,"125,947,217.00",S,2021
2,00.000.000/0001-91,2021-12-31,2,BCO BRASIL S.A.,1023,DF Consolidado - Demonstração do Resultado,REAL,MIL,PENÚLTIMO,2020-01-01,2020-12-31,3.01.01,Receita de Juros,"98,659,704.00",N,2021
3,00.000.000/0001-91,2021-12-31,2,BCO BRASIL S.A.,1023,DF Consolidado - Demonstração do Resultado,REAL,MIL,ÚLTIMO,2021-01-01,2021-12-31,3.01.01,Receita de Juros,"125,947,217.00",N,2021
4,00.000.000/0001-91,2021-12-31,2,BCO BRASIL S.A.,1023,DF Consolidado - Demonstração do Resultado,REAL,MIL,PENÚLTIMO,2020-01-01,2020-12-31,3.02,Despesas de Intermediação Financeira,"-43,232,120.00",S,2021

In [15]:
df_dre

,CNPJ_CIA,DT_REFER,VERSAO,DENOM_CIA,CD_CVM,GRUPO_DFP,MOEDA,ESCALA_MOEDA,ORDEM_EXERC,DT_INI_EXERC,DT_FIM_EXERC,CD_CONTA,DS_CONTA,VL_CONTA,ST_CONTA_FIXA,ANO_ARQUIVO
0,00.000.000/0001-91,2021-12-31,2,BCO BRASIL S.A.,1023,DF Consolidado - Demonstração do Resultado,REAL,MIL,PENÚLTIMO,2020-01-01,2020-12-31,3.01,Receitas de Intermediação Financeira,9.865970e+07,S,2021
1,00.000.000/0001-91,2021-12-31,2,BCO BRASIL S.A.,1023,DF Consolidado - Demonstração do Resultado,REAL,MIL,ÚLTIMO,2021-01-01,2021-12-31,3.01,Receitas de Intermediação Financeira,1.259472e+08,S,2021
2,00.000.000/0001-91,2021-12-31,2,BCO BRASIL S.A.,1023,DF Consolidado - Demonstração do Resultado,REAL,MIL,PENÚLTIMO,2020-01-01,2020-12-31,3.01.01,Receita de Juros,9.865970e+07,N,2021
3,00.000.000/0001-91,2021-12-31,2,BCO BRASIL S.A.,1023,DF Consolidado - Demonstração do Resultado,REAL,MIL,ÚLTIMO,2021-01-01,2021-12-31,3.01.01,Receita de Juros,1.259472e+08,N,2021
4,00.000.000/0001-91,2021-12-31,2,BCO BRASIL S.A.,1023,DF Consolidado - Demonstração do Resultado,REAL,MIL,PENÚLTIMO,2020-01-01,2020-12-31,3.02,Despesas de Intermediação Financeira,-4.323212e+07,S,2021
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
163955,97.837.181/0001-47,2025-12-31,1,DEXCO S.A.,21091,DF Consolidado - Demonstração do Resultado,REAL,MIL,ÚLTIMO,2025-01-01,2025-12-31,3.99.01.01,ON,1.400000e-03,N,2025
163956,97.837.181/0001-47,2025-12-31,1,DEXCO S.A.,21091,DF Consolidado - Demonstração do Resultado,REAL,MIL,PENÚLTIMO,2024-01-01,2024-12-31,3.99.02,Lucro Diluído por Ação,0.000000e+00,N,2025
163957,97.837.181/0001-47,2025-12-31,1,DEXCO S.A.,21091,DF Consolidado - Demonstração do Resultado,REAL,MIL,ÚLTIMO,2025-01-01,2025-12-31,3.99.02,Lucro Diluído por Ação,0.000000e+00,N,2025
163958,97.837.181/0001-47,2025-12-31,1,DEXCO S.A.,21091,DF Consolidado - Demonstração do Resultado,REAL,MIL,PENÚLTIMO,2024-01-01,2024-12-31,3.99.02.01,ON,2.126000e-01,N,2025
163959,97.837.181/0001-47,2025-12-31,1,DEXCO S.A.,21091,DF Consolidado - Demonstração do Resultado,REAL,MIL,ÚLTIMO,2025-01-01,2025-12-31,3.99.02.01,ON,1.400000e-03,N,2025

In [56]:
caminho_tipo = f"../data/raw/TIPO/cad_cia_aberta.csv"
df_tipo = pd.read_csv(caminho_tipo,sep=";",encoding="latin1")
df_tipo.columns.to_list() # procurando o Setor da empresa

['CNPJ_CIA',
 'DENOM_SOCIAL',
 'DENOM_COMERC',
 'DT_REG',
 'DT_CONST',
 'DT_CANCEL',
 'MOTIVO_CANCEL',
 'SIT',
 'DT_INI_SIT',
 'CD_CVM',
 'SETOR_ATIV',
 'TP_MERC',
 'CATEG_REG',
 'DT_INI_CATEG',
 'SIT_EMISSOR',
 'DT_INI_SIT_EMISSOR',
 'CONTROLE_ACIONARIO',
 'TP_ENDER',
 'LOGRADOURO',
 'COMPL',
 'BAIRRO',
 'MUN',
 'UF',
 'PAIS',
 'CEP',
 'DDD_TEL',
 'TEL',
 'DDD_FAX',
 'FAX',
 'EMAIL',
 'TP_RESP',
 'RESP',
 'DT_INI_RESP',
 'LOGRADOURO_RESP',
 'COMPL_RESP',
 'BAIRRO_RESP',
 'MUN_RESP',
 'UF_RESP',
 'PAIS_RESP',
 'CEP_RESP',
 'DDD_TEL_RESP',
 'TEL_RESP',
 'DDD_FAX_RESP',
 'FAX_RESP',
 'EMAIL_RESP',
 'CNPJ_AUDITOR',
 'AUDITOR']

In [ ]:
df_tipo['SETOR_ATIV'].to_list() # Aqui eu to dando so uma olhada se realmente é o que eu pensei.

['Energia Elétrica',
 'Securitização de Recebíveis',
 'Emp. Adm. Part. - Energia Elétrica',
 'Emp. Adm. Part. - Sem Setor Principal',
 'Emp. Adm. Part. - Sem Setor Principal',
 'Emp. Adm. Participações',
 'Emp. Adm. Participações',
 'Máquinas, Equipamentos, Veículos e Peças',
 'Comércio (Atacado e Varejo)',
 'Máquinas, Equipamentos, Veículos e Peças',
 'Arrendamento Mercantil',
 'Gráficas e Editoras',
 'Emp. Adm. Part. - Const. Civil, Mat. Const. e Decoração',
 'Metalurgia e Siderurgia',
 'Metalurgia e Siderurgia',
 'Metalurgia e Siderurgia',
 'Metalurgia e Siderurgia',
 'Metalurgia e Siderurgia',
 'Metalurgia e Siderurgia',
 'Metalurgia e Siderurgia',
 'Petroquímicos e Borracha',
 'Securitização de Recebíveis',
 'Emp. Adm. Participações',
 'Agricultura (Açúcar, Álcool e Cana)',
 'Emp. Adm. Participações',
 'Petroquímicos e Borracha',
 'Petroquímicos e Borracha',
 'Farmacêutico e Higiene',
 'Saneamento, Serv. Água e Gás',
 'Máquinas, Equipamentos, Veículos e Peças',
 'Máquinas, Equipamentos, Veículos e Peças',
 'Serviços Diversos',
 'Emp. Adm. Part. - Energia Elétrica',
 'Emp. Adm. Part. - Energia Elétrica',
 'Emp. Adm. Part. - Energia Elétrica',
 'Energia Elétrica',
 'Energia Elétrica',
 'Securitização de Recebíveis',
 'Energia Elétrica',
 'Energia Elétrica',
 'Seguradoras e Corretoras',
 'Gráficas e Editoras',
 'Petróleo e Gás',
 'Construção Civil, Mat. Constr. e Decoração',
 'Máquinas, Equipamentos, Veículos e Peças',
 'Construção Civil, Mat. Constr. e Decoração',
 'Arrendamento Mercantil',
 'Agricultura (Açúcar, Álcool e Cana)',
 'Comércio (Atacado e Varejo)',
 'Agricultura (Açúcar, Álcool e Cana)',
 'Agricultura (Açúcar, Álcool e Cana)',
 'Saneamento, Serv. Água e Gás',
 'Saneamento, Serv. Água e Gás',
 'Saneamento, Serv. Água e Gás',
 'Saneamento, Serv. Água e Gás',
 'Saneamento, Serv. Água e Gás',
 'Saneamento, Serv. Água e Gás',
 'Saneamento, Serv. Água e Gás',
 'Saneamento, Serv. Água e Gás',
 'Emp. Adm. Part. - Serviços Transporte e Logística',
 'Outras Atividades Industriais',
 'Emp. Adm. Part. - Sem Setor Principal',
 'Emp. Adm. Part. - Telecomunicações',
 'Emp. Adm. Participações',
 'Emp. Adm. Participações',
 'Petroquímicos e Borracha',
 'Metalurgia e Siderurgia',
 'Metalurgia e Siderurgia',
 'Emp. Adm. Part. - Intermediação Financeira',
 'Têxtil e Vestuário',
 'Têxtil e Vestuário',
 'Telecomunicações',
 'Emp. Adm. Part. - Comércio (Atacado e Varejo)',
 'Emp. Adm. Participações',
 'Emp. Adm. Participações',
 'Emp. Adm. Part. - Agricultura (Açúcar, Álcool e Cana)',
 'Emp. Adm. Part. - Sem Setor Principal',
 'Serviços Médicos',
 'Comércio (Atacado e Varejo)',
 'Comércio (Atacado e Varejo)',
 'Emp. Adm. Part. - Sem Setor Principal',
 'Emp. Adm. Part. - Comércio (Atacado e Varejo)',
 'Emp. Adm. Part. - Comércio (Atacado e Varejo)',
 'Serviços Transporte e Logística',
 'Serviços Transporte e Logística',
 'Metalurgia e Siderurgia',
 'Emp. Adm. Part. - Comércio (Atacado e Varejo)',
 'Têxtil e Vestuário',
 'Têxtil e Vestuário',
 'Emp. Adm. Participações',
 'Emp. Adm. Part. - Seguradoras e Corretoras',
 'Construção Civil, Mat. Constr. e Decoração',
 'Máquinas, Equipamentos, Veículos e Peças',
 'Construção Civil, Mat. Constr. e Decoração',
 'Telecomunicações',
 'Securitização de Recebíveis',
 'Farmacêutico e Higiene',
 'Máquinas, Equipamentos, Veículos e Peças',
 'Metalurgia e Siderurgia',
 'Emp. Adm. Participações',
 'Emp. Adm. Part. - Energia Elétrica',
 'Metalurgia e Siderurgia',
 'Emp. Adm. Part. - Sem Setor Principal',
 'Bancos',
 'Metalurgia e Siderurgia',
 'Emp. Adm. Part. - Energia Elétrica',
 'Emp. Adm. Participações',
 'Têxtil e Vestuário',
 'Hospedagem e Turismo',
 'Telecomunicações',
 'Bebidas e Fumo',
 'Bebidas e Fumo',
 'Saneamento, Serv. Água e Gás',
 'Saneamento, Serv. Água e Gás',
 'Máquinas, Equipamentos, Veículos e Peças',
 'Arrendamento Mercantil',
 'Comércio (Atacado e Varejo)',
 'Comércio (Atacado e Varejo)',
 'Hospedagem e Turismo',
 'Telecomunicações',
 'Serviços Médicos',
 'Emp. Adm. Part. - Têxtil e Vestuário',
 'Energia Elétrica',
 'Emp. Adm. Part. - Energia Elétrica',
 'Emp. Adm. Part. - Comércio (Atacado e Varejo)',
 'Emp. Adm. Participações',
 'Máquinas, Equipamentos, Veículos e Peças',
 'Alimentos',
 'Emp. Adm. Part. - Sem Setor Principal',
 'Emp. Adm. Part. - Sem Setor Principal',
 'Energia Elétrica',
 'Emp. Adm. Part. - Educação',
 'Educação',
 'Construção Civil, Mat. Constr. e Decoração',
 'Metalurgia e Siderurgia',
 'Brinquedos e Lazer',
 'Petroquímicos e Borracha',
 'Securitização de Recebíveis',
 'Securitização de Recebíveis',
 'Papel e Celulose',
 'Petroquímicos e Borracha',
 'Alimentos',
 'Extração Mineral',
 'Emp. Adm. Part. - Intermediação Financeira',
 'Comércio (Atacado e Varejo)',
 'Emp. Adm. Part. - Sem Setor Principal',
 'Emp. Adm. Participações',
 'Metalurgia e Siderurgia',
 'Metalurgia e Siderurgia',
 'Metalurgia e Siderurgia',
 'Emp. Adm. Participações',
 'Emp. Adm. Participações',
 'Emp. Adm. Part. - Energia Elétrica',
 'Energia Elétrica',
 'Energia Elétrica',
 'Energia Elétrica',
 'Emp. Adm. Part. - Telecomunicações',
 'Emp. Adm. Part. - Telecomunicações',
 'Serviços Transporte e Logística',
 'Serviços Transporte e Logística',
 'Serviços Transporte e Logística',
 'Máquinas, Equipamentos, Veículos e Peças',
 'Outras Atividades Industriais',
 'Serviços Transporte e Logística',
 'Têxtil e Vestuário',
 'Emp. Adm. Part. - Energia Elétrica',
 'Outras Atividades Industriais',
 'Metalurgia e Siderurgia',
 'Emp. Adm. Part. - Energia Elétrica',
 'Emp. Adm. Part. - Comércio (Atacado e Varejo)',
 'Emp. Adm. Part. - Comércio (Atacado e Varejo)',
 'Emp. Adm. Part. - Serviços médicos',
 'Emp. Adm. Part. - Sem Setor Principal',
 'Telecomunicações',
 'Construção Civil, Mat. Constr. e Decoração',
 'Brinquedos e Lazer',
 'Petroquímicos e Borracha',
 'Farmacêutico e Higiene',
 'Educação',
 'Securitização de Recebíveis',
 'Emp. Adm. Part. - Extração Mineral',
 'Energia Elétrica',
 'Energia Elétrica',
 'Emp. Adm. Part. - Energia Elétrica',
 'Energia Elétrica',
 'Emp. Adm. Participações',
 'Emp. Adm. Part. - Serviços Transporte e Logística',
 'Máquinas, Equipamentos, Veículos e Peças',
 'Máquinas, Equipamentos, Veículos e Peças',
 'Serviços Transporte e Logística',
 'Emp. Adm. Part. - Comércio (Atacado e Varejo)',
 'Serviços Transporte e Logística',
 'Serviços Transporte e Logística',
 'Serviços Transporte e Logística',
 'Serviços Transporte e Logística',
 'Serviços Transporte e Logística',
 'Serviços Transporte e Logística',
 'Serviços Transporte e Logística',
 'Arrendamento Mercantil',
 'Emp. Adm. Participações',
 'Securitização de Recebíveis',
 'Securitização de Recebíveis',
 'Emp. Adm. Participações',
 'Energia Elétrica',
 'Energia Elétrica',
 'Emp. Adm. Part. - Energia Elétrica',
 'Energia Elétrica',
 'Energia Elétrica',
 'Petróleo e Gás',
 'Construção Civil, Mat. Constr. e Decoração',
 'Emp. Adm. Part. - Serviços Transporte e Logística',
 'Têxtil e Vestuário',
 'Securitização de Recebíveis',
 'Intermediação Financeira',
 'Bolsas de Valores/Mercadorias e Futuros',
 'Bolsas de Valores/Mercadorias e Futuros',
 'Papel e Celulose',
 'Energia Elétrica',
 'Agricultura (Açúcar, Álcool e Cana)',
 'Máquinas, Equipamentos, Veículos e Peças',
 'Hospedagem e Turismo',
 'Serviços Diversos',
 'Emp. Adm. Part. - Sem Setor Principal',
 'Crédito Imobiliário',
 'Bancos',
 'Emp. Adm. Part. - Intermediação Financeira',
 'Bancos',
 'Intermediação Financeira',
 'Bancos',
 'Bancos',
 'Bancos',
 'Bancos',
 'Bancos',
 'Bancos',
 'Bancos',
 'Bancos',
 'Bancos',
 'Bancos',
 'Bancos',
 'Bancos',
 'Bancos',
 'Bancos',
 'Bancos',
 'Bancos',
 'Bancos',
 'Bancos',
 'Bancos',
 'Bancos',
 'Bancos',
 'Bancos',
 'Bancos',
 'Bancos',
 'Bancos',
 'Bancos',
 'Bancos',
 'Bancos',
 'Bancos',
 'Bancos',
 'Bancos',
 'Bancos',
 'Bancos',
 'Bancos',
 'Bancos',
 'Bancos',
 'Bancos',
 'Bancos',
 'Bancos',
 'Bancos',
 'Bancos',
 'Bancos',
 'Arrendamento Mercantil',
 'Arrendamento Mercantil',
 'Bancos',
 'Bancos',
 'Bancos',
 'Bancos',
 'Bancos',
 'Bancos',
 'Bancos',
 'Bancos',
 'Bancos',
 'Bancos',
 'Bancos',
 'Bancos',
 'Bancos',
 'Bancos',
 'Bancos',
 'Bancos',
 'Bancos',
 'Bancos',
 nan,
 'Bancos',
 'Bancos',
 'Bancos',
 'Bancos',
 'Arrendamento Mercantil',
 'Arrendamento Mercantil',
 'Arrendamento Mercantil',
 'Bancos',
 'Arrendamento Mercantil',
 'Bancos',
 'Intermediação Financeira',
 'Bancos',
 'Bancos',
 nan,
 'Bancos',
 'Bancos',
 'Bancos',
 'Crédito Imobiliário',
 'Arrendamento Mercantil',
 'Serviços Transporte e Logística',
 'Bancos',
 'Bancos',
 'Têxtil e Vestuário',
 'Emp. Adm. Part. - Sem Setor Principal',
 'Máquinas, Equipamentos, Veículos e Peças',
 'Máquinas, Equipamentos, Veículos e Peças',
 'Securitização de Recebíveis',
 'Alimentos',
 'Securitização de Recebíveis',
 'Emp. Adm. Part. - Sem Setor Principal',
 'Petroquímicos e Borracha',
 'Embalagens',
 'Metalurgia e Siderurgia',
 'Emp. Adm. Part. - Seguradoras e Corretoras',
 'Arrendamento Mercantil',
 'Emp. Adm. Part. - Sem Setor Principal',
 'Arrendamento Mercantil',
 'Serviços Transporte e Logística',
 'Serviços Transporte e Logística',
 'Arrendamento Mercantil',
 'Emp. Adm. Part. - Serviços médicos',
 'Bancos',
 'Bancos',
 'Bancos',
 'Bancos',
 'Bancos',
 'Bancos',
 'Bancos',
 'Bancos',
 'Bancos',
 'Bancos',
 'Telecomunicações',
 'Bancos',
 'Emp. Adm. Part. - Crédito Imobiliário',
 'Energia Elétrica',
 'Emp. Adm. Part. - Sem Setor Principal',
 'Construção Civil, Mat. Constr. e Decoração',
 'Alimentos',
 'Comunicação e Informática',
 'Comunicação e Informática',
 'Petroquímicos e Borracha',
 'Emp. Adm. Part. - Sem Setor Principal',
 'Arrendamento Mercantil',
 'Comércio (Atacado e Varejo)',
 'Securitização de Recebíveis',
 'Emp. Adm. Part. - Crédito Imobiliário',
 'Construção Civil, Mat. Constr. e Decoração',
 'Arrendamento Mercantil',
 'Arrendamento Mercantil',
 'Bancos',
 'Emp. Adm. Part. - Sem Setor Principal',
 'Emp. Adm. Part. - Hospedagem e Turismo',
 'Securitização de Recebíveis',
 'Brinquedos e Lazer',
 'Farmacêutico e Higiene',
 'Emp. Adm. Part. - Educação',
 'Farmacêutico e Higiene',
 'Comunicação e Informática',
 'Agricultura (Açúcar, Álcool e Cana)',
 'Construção Civil, Mat. Constr. e Decoração',
 'Farmacêutico e Higiene',
 'Farmacêutico e Higiene',
 'Alimentos',
 'Hospedagem e Turismo',
 'Brinquedos e Lazer',
 'Securitização de Recebíveis',
 'Arrendamento Mercantil',
 'Arrendamento Mercantil',
 'Bancos',
 'Emp. Adm. Part. - Sem Setor Principal',
 'Alimentos',
 'Comunicação e Informática',
 'Arrendamento Mercantil',
 'Arrendamento Mercantil',
 'Bancos',
 'Têxtil e Vestuário',
 'Emp. Adm. Part. - Sem Setor Principal',
 'Bolsas de Valores/Mercadorias e Futuros',
 'Emp. Adm. Part. - Sem Setor Principal',
 'Farmacêutico e Higiene',
 'Emp. Adm. Part. - Comércio (Atacado e Varejo)',
 'Comércio (Atacado e Varejo)',
 'Serviços Diversos',
 'Emp. Adm. Part. - Energia Elétrica',
 'Construção Civil, Mat. Constr. e Decoração',
 'Construção Civil, Mat. Constr. e Decoração',
 'Petroquímicos e Borracha',
 'Alimentos',
 'Comércio (Atacado e Varejo)',
 'Máquinas, Equipamentos, Veículos e Peças',
 'Petroquímicos e Borracha',
 'Emp. Adm. Participações',
 'Comércio Exterior',
 'Têxtil e Vestuário',
 'Bolsas de Valores/Mercadorias e Futuros',
 'Emp. Adm. Part. - Sem Setor Principal',
 'Construção Civil, Mat. Constr. e Decoração',
 'Emp. Adm. Part. - Comércio (Atacado e Varejo)',
 'Emp. Adm. Part. - Comércio (Atacado e Varejo)',
 'Emp. Adm. Part. - Sem Setor Principal',
 'Emp. Adm. Part. - Sem Setor Principal',
 'Máquinas, Equipamentos, Veículos e Peças',
 'Arrendamento Mercantil',
 'Arrendamento Mercantil',
 'Arrendamento Mercantil',
 'Arrendamento Mercantil',
 'Arrendamento Mercantil',
 'Arrendamento Mercantil',
 'Hospedagem e Turismo',
 'Emp. Adm. Part. - Extração Mineral',
 'Emp. Adm. Part. - Intermediação Financeira',
 'Serviços Médicos',
 'Comércio (Atacado e Varejo)',
 'Metalurgia e Siderurgia',
 'Embalagens',
 'Construção Civil, Mat. Constr. e Decoração',
 'Máquinas, Equipamentos, Veículos e Peças',
 'Hospedagem e Turismo',
 'Construção Civil, Mat. Constr. e Decoração',
 'Energia Elétrica',
 'Hospedagem e Turismo',
 'Serviços Transporte e Logística',
 'Alimentos',
 'Alimentos',
 'Securitização de Recebíveis',
 'Securitização de Recebíveis',
 'Telecomunicações',
 'Emp. Adm. Part. - Telecomunicações',
 'Emp. Adm. Part. - Hospedagem e Turismo',
 'Agricultura (Açúcar, Álcool e Cana)',
 'Energia Elétrica',
 'Emp. Adm. Part. - Energia Elétrica',
 'Máquinas, Equipamentos, Veículos e Peças',
 'Extração Mineral',
 'Têxtil e Vestuário',
 'Construção Civil, Mat. Constr. e Decoração',
 'Petroquímicos e Borracha',
 'Emp. Adm. Participações',
 'Máquinas, Equipamentos, Veículos e Peças',
 'Hospedagem e Turismo',
 'Petróleo e Gás',
 'Petróleo e Gás',
 'Securitização de Recebíveis',
 'Emp. Adm. Part. - Comércio (Atacado e Varejo)',
 'Telecomunicações',
 'Emp. Adm. Part. - Crédito Imobiliário',
 'Bancos',
 'Bancos',
 'Emp. Adm. Part. - Bancos',
 'Securitização de Recebíveis',
 'Emp. Adm. Part. - Alimentos',
 'Comércio (Atacado e Varejo)',
 'Brinquedos e Lazer',
 'Emp. Adm. Part. - Telecomunicações',
 'Telecomunicações',
 'Emp. Adm. Part. - Saneamento, Serv. Água e Gás',
 'Emp. Adm. Part. - Saneamento, Serv. Água e Gás',
 'Emp. Adm. Part. - Const. Civil, Mat. Const. e Decoração',
 'Emp. Adm. Part. - Const. Civil, Mat. Const. e Decoração',
 'Securitização de Recebíveis',
 'Securitização de Recebíveis',
 'Securitização de Recebíveis',
 'Securitização de Recebíveis',
 'Securitização de Recebíveis',
 'Securitização de Recebíveis',
 'Comunicação e Informática',
 'Comunicação e Informática',
 'Emp. Adm. Part. - Telecomunicações',
 'Extração Mineral',
 'Construção Civil, Mat. Constr. e Decoração',
 'Emp. Adm. Part.-Bolsas de Valores/Mercadorias e Futuros',
 'Máquinas, Equipamentos, Veículos e Peças',
 nan,
 'Alimentos',
 'Emp. Adm. Part. - Energia Elétrica',
 'Telecomunicações',
 'Securitização de Recebíveis',
 'Comércio (Atacado e Varejo)',
 'Securitização de Recebíveis',
 'Arrendamento Mercantil',
 'Emp. Adm. Part. - Sem Setor Principal',
 'Emp. Adm. Part. - Sem Setor Principal',
 'Alimentos',
 'Têxtil e Vestuário',
 'Têxtil e Vestuário',
 'Serviços Diversos',
 'Alimentos',
 'Alimentos',
 'Petroquímicos e Borracha',
 'Petroquímicos e Borracha',
 'Arrendamento Mercantil',
 'Emp. Adm. Part. - Máqs., Equip., Veíc. e Peças',
 'Serviços Diversos',
 'Têxtil e Vestuário',
 'Emp. Adm. Part. - Hospedagem e Turismo',
 'Emp. Adm. Part. - Sem Setor Principal',
 'Energia Elétrica',
 'Têxtil e Vestuário',
 'Emp. Adm. Part. - Sem Setor Principal',
 'Emp. Adm. Part. - Metalurgia e Siderurgia',
 'Emp. Adm. Participações',
 'Alimentos',
 'Emp. Adm. Part. - Sem Setor Principal',
 'Emp. Adm. Participações',
 'Intermediação Financeira',
 'Seguradoras e Corretoras',
 'Emp. Adm. Part. - Seguradoras e Corretoras',
 'Agricultura (Açúcar, Álcool e Cana)',
 'Agricultura (Açúcar, Álcool e Cana)',
 'Têxtil e Vestuário',
 'Têxtil e Vestuário',
 'Emp. Adm. Participações',
 'Construção Civil, Mat. Constr. e Decoração',
 'Têxtil e Vestuário',
 'Alimentos',
 'Serviços Transporte e Logística',
 'Têxtil e Vestuário',
 'Máquinas, Equipamentos, Veículos e Peças',
 'Securitização de Recebíveis',
 'Emp. Adm. Part. - Comércio (Atacado e Varejo)',
 'Securitização de Recebíveis',
 'Emp. Adm. Part. - Telecomunicações',
 'Emp. Adm. Part. - Sem Setor Principal',
 'Metalurgia e Siderurgia',
 'Alimentos',
 'Alimentos',
 'Extração Mineral',
 'Emp. Adm. Part. - Sem Setor Principal',
 'Petroquímicos e Borracha',
 'Alimentos',
 'Comércio (Atacado e Varejo)',
 'Securitização de Recebíveis',
 nan,
 'Comércio (Atacado e Varejo)',
 'Comércio (Atacado e Varejo)',
 'Comércio (Atacado e Varejo)',
 'Emp. Adm. Participações',
 'Agricultura (Açúcar, Álcool e Cana)',
 'Alimentos',
 'Emp. Adm. Part. - Sem Setor Principal',
 'Construção Civil, Mat. Constr. e Decoração',
 'Construção Civil, Mat. Constr. e Decoração',
 'Emp. Adm. Part. - Petróleo e Gás',
 'Máquinas, Equipamentos, Veículos e Peças',
 'Máquinas, Equipamentos, Veículos e Peças',
 'Máquinas, Equipamentos, Veículos e Peças',
 'Arrendamento Mercantil',
 'Petroquímicos e Borracha',
 'Máquinas, Equipamentos, Veículos e Peças',
 'Emp. Adm. Part. - Extração Mineral',
 'Serviços Transporte e Logística',
 'Extração Mineral',
 'Construção Civil, Mat. Constr. e Decoração',
 'Construção Civil, Mat. Constr. e Decoração',
 'Emp. Adm. Part. - Educação',
 'Emp. Adm. Part. - Energia Elétrica',
 'Extração Mineral',
 'Máquinas, Equipamentos, Veículos e Peças',
 'Emp. Adm. Part. - Telecomunicações',
 'Máquinas, Equipamentos, Veículos e Peças',
 'Emp. Adm. Part. - Sem Setor Principal',
 'Energia Elétrica',
 'Energia Elétrica',
 'Telecomunicações',
 'Comércio (Atacado e Varejo)',
 'Emp. Adm. Part. - Extração Mineral',
 'Emp. Adm. Part. - Serviços Transporte e Logística',
 'Energia Elétrica',
 'Energia Elétrica',
 'Serviços Médicos',
 'Construção Civil, Mat. Constr. e Decoração',
 'Serviços Transporte e Logística',
 'Máquinas, Equipamentos, Veículos e Peças',
 'Construção Civil, Mat. Constr. e Decoração',
 'Extração Mineral',
 'Extração Mineral',
 'Extração Mineral',
 'Extração Mineral',
 'Securitização de Recebíveis',
 'Agricultura (Açúcar, Álcool e Cana)',
 'Energia Elétrica',
 'Energia Elétrica',
 'Construção Civil, Mat. Constr. e Decoração',
 'Telecomunicações',
 'Intermediação Financeira',
 'Intermediação Financeira',
 'Outras Atividades Industriais',
 'Petroquímicos e Borracha',
 'Alimentos',
 'Alimentos',
 'Arrendamento Mercantil',
 'Emp. Adm. Participações',
 'Energia Elétrica',
 'Alimentos',
 'Agricultura (Açúcar, Álcool e Cana)',
 'Alimentos',
 'Petroquímicos e Borracha',
 'Têxtil e Vestuário',
 'Bancos',
 'Emp. Adm. Participações',
 'Serviços Transporte e Logística',
 'Bancos',
 'Emp. Adm. Part. - Têxtil e Vestuário',
 'Emp. Adm. Participações',
 'Construção Civil, Mat. Constr. e Decoração',
 'Petroquímicos e Borracha',
 'Construção Civil, Mat. Constr. e Decoração',
 'Metalurgia e Siderurgia',
 'Alimentos',
 'Saneamento, Serv. Água e Gás',
 'Bebidas e Fumo',
 'Bebidas e Fumo',
 'Extração Mineral',
 'Extração Mineral',
 'Extração Mineral',
 'Extração Mineral',
 'Extração Mineral',
 'Máquinas, Equipamentos, Veículos e Peças',
 'Máquinas, Equipamentos, Veículos e Peças',
 'Construção Civil, Mat. Constr. e Decoração',
 'Saneamento, Serv. Água e Gás',
 'Energia Elétrica',
 'Emp. Adm. Part. - Sem Setor Principal',
 'Emp. Adm. Part. - Sem Setor Principal',
 'Petróleo e Gás',
 'Agricultura (Açúcar, Álcool e Cana)',
 'Agricultura (Açúcar, Álcool e Cana)',
 'Serviços Transporte e Logística',
 'Energia Elétrica',
 'Energia Elétrica',
 'Energia Elétrica',
 'Energia Elétrica',
 'Energia Elétrica',
 'Saneamento, Serv. Água e Gás',
 'Energia Elétrica',
 'Têxtil e Vestuário',
 'Têxtil e Vestuário',
 'Metalurgia e Siderurgia',
 'Metalurgia e Siderurgia',
 'Têxtil e Vestuário',
 'Metalurgia e Siderurgia',
 'Têxtil e Vestuário',
 'Têxtil e Vestuário',
 'Agricultura (Açúcar, Álcool e Cana)',
 'Metalurgia e Siderurgia',
 'Metalurgia e Siderurgia',
 'Alimentos',
 'Metalurgia e Siderurgia',
 'Têxtil e Vestuário',
 'Extração Mineral',
 'Alimentos',
 'Têxtil e Vestuário',
 'Alimentos',
 'Metalurgia e Siderurgia',
 'Têxtil e Vestuário',
 'Máquinas, Equipamentos, Veículos e Peças',
 'Têxtil e Vestuário',
 'Emp. Adm. Participações',
 'Emp. Adm. Participações',
 'Emp. Adm. Participações',
 'Emp. Adm. Participações',
 'Emp. Adm. Participações',
 'Alimentos',
 'Têxtil e Vestuário',
 'Construção Civil, Mat. Constr. e Decoração',
 'Bebidas e Fumo',
 'Extração Mineral',
 'Alimentos',
 'Pesca',
 'Petroquímicos e Borracha',
 'Têxtil e Vestuário',
 'Serviços Transporte e Logística',
 'Petroquímicos e Borracha',
 'Extração Mineral',
 'Emp. Adm. Participações',
 'Metalurgia e Siderurgia',
 'Energia Elétrica',
 'Petroquímicos e Borracha',
 'Serviços Diversos',
 'Petróleo e Gás',
 'Energia Elétrica',
 'Petroquímicos e Borracha',
 'Serviços Transporte e Logística',
 'Têxtil e Vestuário',
 'Securitização de Recebíveis',

In [57]:
cad_setor = df_tipo[["CD_CVM", "SETOR_ATIV"]]
df_dre = df_dre.merge(cad_setor, on="CD_CVM", how="left")

print(df_dre["SETOR_ATIV"].isna().sum())  # confere quantas linhas ficaram sem setor (NaN)
df_dre.head()

1822

,CNPJ_CIA,DT_REFER,VERSAO,DENOM_CIA,CD_CVM,GRUPO_DFP,MOEDA,ESCALA_MOEDA,ORDEM_EXERC,DT_INI_EXERC,DT_FIM_EXERC,CD_CONTA,DS_CONTA,VL_CONTA,ST_CONTA_FIXA,ANO_ARQUIVO,SETOR_ATIV
0,00.000.000/0001-91,2021-12-31,2,BCO BRASIL S.A.,1023,DF Consolidado - Demonstração do Resultado,REAL,MIL,PENÚLTIMO,2020-01-01,2020-12-31,3.01,Receitas de Intermediação Financeira,"98,659,704.00",S,2021,Bancos
1,00.000.000/0001-91,2021-12-31,2,BCO BRASIL S.A.,1023,DF Consolidado - Demonstração do Resultado,REAL,MIL,ÚLTIMO,2021-01-01,2021-12-31,3.01,Receitas de Intermediação Financeira,"125,947,217.00",S,2021,Bancos
2,00.000.000/0001-91,2021-12-31,2,BCO BRASIL S.A.,1023,DF Consolidado - Demonstração do Resultado,REAL,MIL,PENÚLTIMO,2020-01-01,2020-12-31,3.01.01,Receita de Juros,"98,659,704.00",N,2021,Bancos
3,00.000.000/0001-91,2021-12-31,2,BCO BRASIL S.A.,1023,DF Consolidado - Demonstração do Resultado,REAL,MIL,ÚLTIMO,2021-01-01,2021-12-31,3.01.01,Receita de Juros,"125,947,217.00",N,2021,Bancos
4,00.000.000/0001-91,2021-12-31,2,BCO BRASIL S.A.,1023,DF Consolidado - Demonstração do Resultado,REAL,MIL,PENÚLTIMO,2020-01-01,2020-12-31,3.02,Despesas de Intermediação Financeira,"-43,232,120.00",S,2021,Bancos

In [25]:
df_dre.groupby("SETOR_ATIV")["CNPJ_CIA"].nunique().sort_values(ascending=False)

SETOR_ATIV
Construção Civil, Mat. Constr. e Decoração                 50
Comércio (Atacado e Varejo)                                44
Energia Elétrica                                           36
Serviços Transporte e Logística                            30
Emp. Adm. Part. - Energia Elétrica                         26
Máquinas, Equipamentos, Veículos e Peças                   23
Têxtil e Vestuário                                         21
Comunicação e Informática                                  21
Bancos                                                     20
Emp. Adm. Part. - Sem Setor Principal                      17
Serviços Médicos                                           16
Agricultura (Açúcar, Álcool e Cana)                        15
Emp. Adm. Part. - Serviços Transporte e Logística          14
Alimentos                                                  14
Metalurgia e Siderurgia                                    14
Telecomunicações                                           14
Emp. Adm. Part. - Const. Civil, Mat. Const. e Decoração    13
Saneamento, Serv. Água e Gás                               11
Emp. Adm. Part. - Comércio (Atacado e Varejo)               9
Educação                                                    9
Farmacêutico e Higiene                                      9
Petróleo e Gás                                              8
Emp. Adm. Part. - Telecomunicações                          6
Petroquímicos e Borracha                                    6
Emp. Adm. Part. - Petróleo e Gás                            5
Seguradoras e Corretoras                                    5
Emp. Adm. Part. - Educação                                  5
Brinquedos e Lazer                                          5
Emp. Adm. Part. - Alimentos                                 4
Emp. Adm. Part. - Intermediação Financeira                  4
Intermediação Financeira                                    4
Papel e Celulose                                            4
Emp. Adm. Part. - Metalurgia e Siderurgia                   4
Emp. Adm. Part. - Máqs., Equip., Veíc. e Peças              4
Emp. Adm. Part. - Comunicação e Informática                 4
Emp. Adm. Part. - Seguradoras e Corretoras                  4
Emp. Adm. Part. - Extração Mineral                          3
Emp. Adm. Part. - Serviços médicos                          3
Hospedagem e Turismo                                        3
Extração Mineral                                            3
Emp. Adm. Part. - Têxtil e Vestuário                        3
Emp. Adm. Part. - Agricultura (Açúcar, Álcool e Cana)       3
Bebidas e Fumo                                              2
Emp. Adm. Part. - Brinquedos e Lazer                        2
Emp. Adm. Part. - Saneamento, Serv. Água e Gás              2
Securitização de Recebíveis                                 2
Emp. Adm. Part. - Crédito Imobiliário                       2
Emp. Adm. Part. - Bancos                                    1
Embalagens                                                  1
Bolsas de Valores/Mercadorias e Futuros                     1
Emp. Adm. Part. - Papel e Celulose                          1
Name: CNPJ_CIA, dtype: int64

In [26]:
df_dre

,CNPJ_CIA,DT_REFER,VERSAO,DENOM_CIA,CD_CVM,GRUPO_DFP,MOEDA,ESCALA_MOEDA,ORDEM_EXERC,DT_INI_EXERC,DT_FIM_EXERC,CD_CONTA,DS_CONTA,VL_CONTA,ST_CONTA_FIXA,ANO_ARQUIVO,SETOR_ATIV
0,00.000.000/0001-91,2021-12-31,2,BCO BRASIL S.A.,1023,DF Consolidado - Demonstração do Resultado,REAL,MIL,PENÚLTIMO,2020-01-01,2020-12-31,3.01,Receitas de Intermediação Financeira,9.865970e+07,S,2021,Bancos
1,00.000.000/0001-91,2021-12-31,2,BCO BRASIL S.A.,1023,DF Consolidado - Demonstração do Resultado,REAL,MIL,ÚLTIMO,2021-01-01,2021-12-31,3.01,Receitas de Intermediação Financeira,1.259472e+08,S,2021,Bancos
2,00.000.000/0001-91,2021-12-31,2,BCO BRASIL S.A.,1023,DF Consolidado - Demonstração do Resultado,REAL,MIL,PENÚLTIMO,2020-01-01,2020-12-31,3.01.01,Receita de Juros,9.865970e+07,N,2021,Bancos
3,00.000.000/0001-91,2021-12-31,2,BCO BRASIL S.A.,1023,DF Consolidado - Demonstração do Resultado,REAL,MIL,ÚLTIMO,2021-01-01,2021-12-31,3.01.01,Receita de Juros,1.259472e+08,N,2021,Bancos
4,00.000.000/0001-91,2021-12-31,2,BCO BRASIL S.A.,1023,DF Consolidado - Demonstração do Resultado,REAL,MIL,PENÚLTIMO,2020-01-01,2020-12-31,3.02,Despesas de Intermediação Financeira,-4.323212e+07,S,2021,Bancos
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
194243,97.837.181/0001-47,2025-12-31,1,DEXCO S.A.,21091,DF Consolidado - Demonstração do Resultado,REAL,MIL,ÚLTIMO,2025-01-01,2025-12-31,3.99.02,Lucro Diluído por Ação,0.000000e+00,N,2025,"Construção Civil, Mat. Constr. e Decoração"
194244,97.837.181/0001-47,2025-12-31,1,DEXCO S.A.,21091,DF Consolidado - Demonstração do Resultado,REAL,MIL,PENÚLTIMO,2024-01-01,2024-12-31,3.99.02.01,ON,2.126000e-01,N,2025,"Construção Civil, Mat. Constr. e Decoração"
194245,97.837.181/0001-47,2025-12-31,1,DEXCO S.A.,21091,DF Consolidado - Demonstração do Resultado,REAL,MIL,PENÚLTIMO,2024-01-01,2024-12-31,3.99.02.01,ON,2.126000e-01,N,2025,"Construção Civil, Mat. Constr. e Decoração"
194246,97.837.181/0001-47,2025-12-31,1,DEXCO S.A.,21091,DF Consolidado - Demonstração do Resultado,REAL,MIL,ÚLTIMO,2025-01-01,2025-12-31,3.99.02.01,ON,1.400000e-03,N,2025,"Construção Civil, Mat. Constr. e Decoração"
194247,97.837.181/0001-47,2025-12-31,1,DEXCO S.A.,21091,DF Consolidado - Demonstração do Resultado,REAL,MIL,ÚLTIMO,2025-01-01,2025-12-31,3.99.02.01,ON,1.400000e-03,N,2025,"Construção Civil, Mat. Constr. e Decoração"

In [30]:
df_dre[df_dre["DS_CONTA"].str.contains("Lucro", case=False, na=False)]["CD_CONTA"].unique()

<ArrowStringArray>
[      '3.05',       '3.06',       '3.07',       '3.09',       '3.10',
       '3.11',       '3.99',    '3.99.01',    '3.99.02',       '3.08',
    '3.10.01',    '3.08.01', '3.04.05.04', '3.04.04.02',    '3.12.01',
       '3.13', '3.04.05.02', '3.04.02.03', '3.10.02.01', '3.04.05.01',
    '3.05.07', '3.10.01.01', '3.10.01.02', '3.04.06.01', '3.10.01.03']
Length: 25, dtype: str

In [34]:
df_dre[df_dre["DS_CONTA"].str.contains("Lucro", case=False, na=False)][["DS_CONTA", "CD_CONTA"]].drop_duplicates().sort_values("CD_CONTA")

                                                 DS_CONTA    CD_CONTA
23352             Participação dos colab. e adm. no lucro  3.04.02.03
36048     Programa de Participação dos Lucros e Resultado  3.04.02.03
14420                      Ganho na distribuição de lucro  3.04.04.02
24392   Lucro Proveniente da Alienação de Bens do Ativ...  3.04.04.02
35798              Participação dos Funcionários no Lucro  3.04.05.01
18386                Participação dos Empregados no Lucro  3.04.05.02
57908               Participações dos Empregados no Lucro  3.04.05.02
9064                  Participação de Empregados no Lucro  3.04.05.04
23454               Participação nos Lucros ou Resultados  3.04.05.04
142706  Participação nos lucros de coligadas, controla...  3.04.06.01
42             Resultado antes dos Tributos sobre o Lucro        3.05
752            Resultado Antes dos Tributos sobre o Lucro        3.05
56552               Participações nos Lucros - Empregados     3.05.07
44      Imposto de Renda e Contribuição Social sobre o...        3.06
50            Lucro ou Prejuízo das Operações Continuadas        3.07
230            Resultado Antes dos Tributos sobre o Lucro        3.07
232     Imposto de Renda e Contribuição Social sobre o...        3.08
764     Lucro/Prejuízo Líquido das Operações Descontin...     3.08.01
18026    Lucro/Prejuízo Líquido das Operações Desconti...     3.08.01
54      Lucro ou Prejuízo antes das Participações e Co...        3.09
768                 Lucro/Prejuízo Consolidado do Período        3.09
16914          Resultado Antes dos Tributos sobre o Lucro        3.09
56      Participações nos Lucros e Contribuições Estat...        3.10
16916   Imposto de Renda e Contribuição Social sobre o...        3.10
242     Lucro/Prejuízo Líquido das Operações Descontin...     3.10.01
188960  Participações nos Lucros e Contribuições Estat...     3.10.01
66444                       Incentivo lucro da exploração  3.10.01.01
69082       Lucro/Prejuízo Líquido da Dimensão de Techfin  3.10.01.01
69084      Lucro/Prejuízo Líquido da Operação de Hardware  3.10.01.02
184986  Lucro/Prejuízo Líquido da Operação Descontinua...  3.10.01.02
184988  Lucro/Prejuízo Líquido da Operação Descontinua...  3.10.01.03
31704   Lucro/Prejuizo Liquido das Operações Descontin...  3.10.02.01
93980   Participação nos lucros de empresas investidas...  3.10.02.01
58       Lucro ou Prejuízo Líquido Consolidado do Período        3.11
246                 Lucro/Prejuízo Consolidado do Período        3.11
16926   Lucro/Prejuízo Líquido das Operações Descontin...     3.12.01
16932               Lucro/Prejuízo Consolidado do Período        3.13
64                               Lucro por Ação (R$/Ação)        3.99
252                       Lucro por Ação - (Reais / Ação)        3.99
774                          Lucro por Ação - (R$ / Ação)        3.99
66                                  Lucro Básico por Ação     3.99.01
70                                 Lucro Diluído por Ação     3.99.02

In [ ]:
df_lucro = df_dre[df_dre["CD_CONTA"] == "3.11"].copy()

df_lucro_ano = df_lucro.groupby(["DENOM_CIA", "SETOR_ATIV", "ANO_ARQUIVO"])["VL_CONTA"].sum().reset_index()
#quero ver o lucro por ano, por empresa e por setor.
df_lucro_ano = df_lucro_ano.sort_values(["ANO_ARQUIVO", "SETOR_ATIV", "VL_CONTA"], ascending=[True, True, False])
#quero fazer em ordem decrescente, do maior lucro para o menor lucro, por ano e por setor.
df_lucro_ano.head(20)

,DENOM_CIA,SETOR_ATIV,ANO_ARQUIVO,VL_CONTA
671,COSAN S.A.,"Agricultura (Açúcar, Álcool e Cana)",2021,14519180.0
1897,SLC AGRICOLA S.A.,"Agricultura (Açúcar, Álcool e Cana)",2021,1641707.0
1847,SAO MARTINHO S.A.,"Agricultura (Açúcar, Álcool e Cana)",2021,1566134.0
1736,RAIZEN ENERGIA S.A.,"Agricultura (Açúcar, Álcool e Cana)",2021,867927.0
342,BRASILAGRO - CIA BRAS DE PROP AGRICOLAS,"Agricultura (Açúcar, Álcool e Cana)",2021,437200.0
461,CERRADINHO BIOENERGIA S.A.,"Agricultura (Açúcar, Álcool e Cana)",2021,373326.0
1235,JALLES MACHADO S.A.,"Agricultura (Açúcar, Álcool e Cana)",2021,246973.0
2169,VITTIA S.A.,"Agricultura (Açúcar, Álcool e Cana)",2021,193673.0
713,CTC - CENTRO DE TECNOLOGIA CANAVIEIRA S.A.,"Agricultura (Açúcar, Álcool e Cana)",2021,127789.0
2007,TERRA SANTA PROPRIEDADES AGRÍCOLAS S.A.,"Agricultura (Açúcar, Álcool e Cana)",2021,74737.0
1553,NUTRIPLANT INDUSTRIA E COMERCIO S.A.,"Agricultura (Açúcar, Álcool e Cana)",2021,10124.0
1674,POMIFRUTAS S/A EM RECUPERACAO JUDICIAL,"Agricultura (Açúcar, Álcool e Cana)",2021,2447.0
295,BIOSEV S.A.,"Agricultura (Açúcar, Álcool e Cana)",2021,-1388206.0
1240,JBS S.A.,Alimentos,2021,25184602.0
1412,MARFRIG GLOBAL FOODS S.A.,Alimentos,2021,11177231.0
1457,MINERVA S.A.,Alimentos,2021,1295971.0
1377,M.DIAS BRANCO S.A. IND COM DE ALIMENTOS,Alimentos,2021,1268830.0
416,CAMIL ALIMENTOS S.A.,Alimentos,2021,702304.0
425,CARAMURU ALIMENTOS S.A.,Alimentos,2021,575710.0
1230,J. MACEDO S.A.,Alimentos,2021,236764.0

In [44]:
#Quero ver apenas os valores que não estão na escala de mil
df_dre[~df_dre["ESCALA_MOEDA"].str.contains("Mil")]

,CNPJ_CIA,DT_REFER,VERSAO,DENOM_CIA,CD_CVM,GRUPO_DFP,MOEDA,ESCALA_MOEDA,ORDEM_EXERC,DT_INI_EXERC,DT_FIM_EXERC,CD_CONTA,DS_CONTA,VL_CONTA,ST_CONTA_FIXA,ANO_ARQUIVO,SETOR_ATIV
0,00.000.000/0001-91,2021-12-31,2,BCO BRASIL S.A.,1023,DF Consolidado - Demonstração do Resultado,REAL,MIL,PENÚLTIMO,2020-01-01,2020-12-31,3.01,Receitas de Intermediação Financeira,9.865970e+07,S,2021,Bancos
1,00.000.000/0001-91,2021-12-31,2,BCO BRASIL S.A.,1023,DF Consolidado - Demonstração do Resultado,REAL,MIL,ÚLTIMO,2021-01-01,2021-12-31,3.01,Receitas de Intermediação Financeira,1.259472e+08,S,2021,Bancos
2,00.000.000/0001-91,2021-12-31,2,BCO BRASIL S.A.,1023,DF Consolidado - Demonstração do Resultado,REAL,MIL,PENÚLTIMO,2020-01-01,2020-12-31,3.01.01,Receita de Juros,9.865970e+07,N,2021,Bancos
3,00.000.000/0001-91,2021-12-31,2,BCO BRASIL S.A.,1023,DF Consolidado - Demonstração do Resultado,REAL,MIL,ÚLTIMO,2021-01-01,2021-12-31,3.01.01,Receita de Juros,1.259472e+08,N,2021,Bancos
4,00.000.000/0001-91,2021-12-31,2,BCO BRASIL S.A.,1023,DF Consolidado - Demonstração do Resultado,REAL,MIL,PENÚLTIMO,2020-01-01,2020-12-31,3.02,Despesas de Intermediação Financeira,-4.323212e+07,S,2021,Bancos
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
194243,97.837.181/0001-47,2025-12-31,1,DEXCO S.A.,21091,DF Consolidado - Demonstração do Resultado,REAL,MIL,ÚLTIMO,2025-01-01,2025-12-31,3.99.02,Lucro Diluído por Ação,0.000000e+00,N,2025,"Construção Civil, Mat. Constr. e Decoração"
194244,97.837.181/0001-47,2025-12-31,1,DEXCO S.A.,21091,DF Consolidado - Demonstração do Resultado,REAL,MIL,PENÚLTIMO,2024-01-01,2024-12-31,3.99.02.01,ON,2.126000e-01,N,2025,"Construção Civil, Mat. Constr. e Decoração"
194245,97.837.181/0001-47,2025-12-31,1,DEXCO S.A.,21091,DF Consolidado - Demonstração do Resultado,REAL,MIL,PENÚLTIMO,2024-01-01,2024-12-31,3.99.02.01,ON,2.126000e-01,N,2025,"Construção Civil, Mat. Constr. e Decoração"
194246,97.837.181/0001-47,2025-12-31,1,DEXCO S.A.,21091,DF Consolidado - Demonstração do Resultado,REAL,MIL,ÚLTIMO,2025-01-01,2025-12-31,3.99.02.01,ON,1.400000e-03,N,2025,"Construção Civil, Mat. Constr. e Decoração"
194247,97.837.181/0001-47,2025-12-31,1,DEXCO S.A.,21091,DF Consolidado - Demonstração do Resultado,REAL,MIL,ÚLTIMO,2025-01-01,2025-12-31,3.99.02.01,ON,1.400000e-03,N,2025,"Construção Civil, Mat. Constr. e Decoração"

In [ ]:
pd.set_option("display.float_format", lambda x: f"{x:,.2f}")
df_lucro_ano["VL_CONTA_REAIS"] = df_lucro_ano["VL_CONTA"] * 1000
df_lucro_ano["VL_CONTA_BI"] = df_lucro_ano["VL_CONTA_REAIS"] / 1_000_000_000

In [62]:
df_lucro_ano

,DENOM_CIA,SETOR_ATIV,ANO_ARQUIVO,VL_CONTA,VL_CONTA_REAIS,VL_CONTA_BI
671,COSAN S.A.,"Agricultura (Açúcar, Álcool e Cana)",2021,"14,519,180.00","14,519,180,000.00",14.52
1897,SLC AGRICOLA S.A.,"Agricultura (Açúcar, Álcool e Cana)",2021,"1,641,707.00","1,641,707,000.00",1.64
1847,SAO MARTINHO S.A.,"Agricultura (Açúcar, Álcool e Cana)",2021,"1,566,134.00","1,566,134,000.00",1.57
1736,RAIZEN ENERGIA S.A.,"Agricultura (Açúcar, Álcool e Cana)",2021,"867,927.00","867,927,000.00",0.87
342,BRASILAGRO - CIA BRAS DE PROP AGRICOLAS,"Agricultura (Açúcar, Álcool e Cana)",2021,"437,200.00","437,200,000.00",0.44
...,...,...,...,...,...,...
508,CIA INDUSTRIAL SCHLOSSER S.A.,Têxtil e Vestuário,2025,-467.00,"-467,000.00",-0.00
941,FIACAO E TECELAGEM SAO JOSE SA EM RECUPERACAO ...,Têxtil e Vestuário,2025,"-17,600.00","-17,600,000.00",-0.02
1523,MUNDIAL S.A. - PRODUTOS DE CONSUMO,Têxtil e Vestuário,2025,"-18,152.00","-18,152,000.00",-0.02
2016,TEXTIL RENAUXVIEW S.A.,Têxtil e Vestuário,2025,"-96,538.00","-96,538,000.00",-0.10
1155,INBRANDS S.A.,Têxtil e Vestuário,2025,"-166,219.00","-166,219,000.00",-0.17

ValueError: Item wrong length 3 instead of 2264.

In [59]:
df_lucro_ano.sort_values("VL_CONTA_REAIS", ascending=False)

,DENOM_CIA,SETOR_ATIV,ANO_ARQUIVO,VL_CONTA,VL_CONTA_REAIS,VL_CONTA_BI
2178,VIVARA PARTICIPAÇÕES S.A.,Comércio (Atacado e Varejo),2025,"1,272,896,247.00","1,272,896,247,000.00","1,272.90"
2177,VIVARA PARTICIPAÇÕES S.A.,Comércio (Atacado e Varejo),2024,"1,022,638,499.00","1,022,638,499,000.00","1,022.64"
2176,VIVARA PARTICIPAÇÕES S.A.,Comércio (Atacado e Varejo),2023,"730,098,970.00","730,098,970,000.00",730.10
2175,VIVARA PARTICIPAÇÕES S.A.,Comércio (Atacado e Varejo),2022,"659,344,688.00","659,344,688,000.00",659.34
1649,PETROLEO BRASILEIRO S.A. PETROBRAS,Petróleo e Gás,2023,"628,342,000.00","628,342,000,000.00",628.34
...,...,...,...,...,...,...
991,GOL LINHAS AEREAS INTELIGENTES S.A.,Emp. Adm. Part. - Serviços Transporte e Logística,2021,"-26,158,110.00","-26,158,110,000.00",-26.16
1570,OI S.A. - EM RECUPERAÇÃO JUDICIAL,Telecomunicações,2022,"-29,673,719.00","-29,673,719,000.00",-29.67
94,AMERICANAS S.A. - EM RECUPERAÇÃO JUDICIAL,Comércio (Atacado e Varejo),2023,"-30,984,000.00","-30,984,000,000.00",-30.98
675,COSAN S.A.,"Agricultura (Açúcar, Álcool e Cana)",2025,"-36,712,334.00","-36,712,334,000.00",-36.71
93,AMERICANAS S.A. - EM RECUPERAÇÃO JUDICIAL,Comércio (Atacado e Varejo),2022,"-38,297,800.00","-38,297,800,000.00",-38.30

In [58]:
df_lucro_ano.loc[df_lucro_ano.groupby("ANO_ARQUIVO")["VL_CONTA"].idxmax()]

,DENOM_CIA,SETOR_ATIV,ANO_ARQUIVO,VL_CONTA,VL_CONTA_REAIS,VL_CONTA_BI
2174,VIVARA PARTICIPAÇÕES S.A.,Comércio (Atacado e Varejo),2021,"445,162,380.00","445,162,380,000.00",445.16
2175,VIVARA PARTICIPAÇÕES S.A.,Comércio (Atacado e Varejo),2022,"659,344,688.00","659,344,688,000.00",659.34
2176,VIVARA PARTICIPAÇÕES S.A.,Comércio (Atacado e Varejo),2023,"730,098,970.00","730,098,970,000.00",730.10
2177,VIVARA PARTICIPAÇÕES S.A.,Comércio (Atacado e Varejo),2024,"1,022,638,499.00","1,022,638,499,000.00","1,022.64"
2178,VIVARA PARTICIPAÇÕES S.A.,Comércio (Atacado e Varejo),2025,"1,272,896,247.00","1,272,896,247,000.00","1,272.90"

In [60]:
df_lucro_ano.to_csv("../data/processed/lucro_liquido_2021_2025.csv", index=False)

NameError: name 'df_bpp' is not defined