In [1]:
import pandas as pd

anos = [2021, 2022, 2023, 2024, 2025]
dfs = []

for ano in anos:
    caminho = f"../data/raw/DRE/dfp_cia_aberta_DRE_con_{ano}.csv"
    df = pd.read_csv(caminho, sep=";", encoding="latin1")
    df["ANO_ARQUIVO"] = ano
    dfs.append(df)
    print(f"{ano}: {df.shape[0]} linhas")  # confere se algum ano veio vazio/suspeito

df_dre = pd.concat(dfs, ignore_index=True)
print("Total:", df_dre.shape)
df_dre.head()

2021: 32644 linhas
2022: 33784 linhas
2023: 33970 linhas
2024: 32776 linhas

2025: 30980 linhas
Total: (164154, 16)

,CNPJ_CIA,DT_REFER,VERSAO,DENOM_CIA,CD_CVM,GRUPO_DFP,MOEDA,ESCALA_MOEDA,ORDEM_EXERC,DT_INI_EXERC,DT_FIM_EXERC,CD_CONTA,DS_CONTA,VL_CONTA,ST_CONTA_FIXA,ANO_ARQUIVO
0,00.000.000/0001-91,2021-12-31,2,BCO BRASIL S.A.,1023,DF Consolidado - Demonstração do Resultado,REAL,MIL,PENÚLTIMO,2020-01-01,2020-12-31,3.01,Receitas de Intermediação Financeira,98659704.0,S,2021
1,00.000.000/0001-91,2021-12-31,2,BCO BRASIL S.A.,1023,DF Consolidado - Demonstração do Resultado,REAL,MIL,ÚLTIMO,2021-01-01,2021-12-31,3.01,Receitas de Intermediação Financeira,125947217.0,S,2021
2,00.000.000/0001-91,2021-12-31,2,BCO BRASIL S.A.,1023,DF Consolidado - Demonstração do Resultado,REAL,MIL,PENÚLTIMO,2020-01-01,2020-12-31,3.01.01,Receita de Juros,98659704.0,N,2021
3,00.000.000/0001-91,2021-12-31,2,BCO BRASIL S.A.,1023,DF Consolidado - Demonstração do Resultado,REAL,MIL,ÚLTIMO,2021-01-01,2021-12-31,3.01.01,Receita de Juros,125947217.0,N,2021
4,00.000.000/0001-91,2021-12-31,2,BCO BRASIL S.A.,1023,DF Consolidado - Demonstração do Resultado,REAL,MIL,PENÚLTIMO,2020-01-01,2020-12-31,3.02,Despesas de Intermediação Financeira,-43232120.0,S,2021

In [2]:
df_dre

,CNPJ_CIA,DT_REFER,VERSAO,DENOM_CIA,CD_CVM,GRUPO_DFP,MOEDA,ESCALA_MOEDA,ORDEM_EXERC,DT_INI_EXERC,DT_FIM_EXERC,CD_CONTA,DS_CONTA,VL_CONTA,ST_CONTA_FIXA,ANO_ARQUIVO
0,00.000.000/0001-91,2021-12-31,2,BCO BRASIL S.A.,1023,DF Consolidado - Demonstração do Resultado,REAL,MIL,PENÚLTIMO,2020-01-01,2020-12-31,3.01,Receitas de Intermediação Financeira,9.865970e+07,S,2021
1,00.000.000/0001-91,2021-12-31,2,BCO BRASIL S.A.,1023,DF Consolidado - Demonstração do Resultado,REAL,MIL,ÚLTIMO,2021-01-01,2021-12-31,3.01,Receitas de Intermediação Financeira,1.259472e+08,S,2021
2,00.000.000/0001-91,2021-12-31,2,BCO BRASIL S.A.,1023,DF Consolidado - Demonstração do Resultado,REAL,MIL,PENÚLTIMO,2020-01-01,2020-12-31,3.01.01,Receita de Juros,9.865970e+07,N,2021
3,00.000.000/0001-91,2021-12-31,2,BCO BRASIL S.A.,1023,DF Consolidado - Demonstração do Resultado,REAL,MIL,ÚLTIMO,2021-01-01,2021-12-31,3.01.01,Receita de Juros,1.259472e+08,N,2021
4,00.000.000/0001-91,2021-12-31,2,BCO BRASIL S.A.,1023,DF Consolidado - Demonstração do Resultado,REAL,MIL,PENÚLTIMO,2020-01-01,2020-12-31,3.02,Despesas de Intermediação Financeira,-4.323212e+07,S,2021
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
164149,97.837.181/0001-47,2025-12-31,1,DEXCO S.A.,21091,DF Consolidado - Demonstração do Resultado,REAL,MIL,ÚLTIMO,2025-01-01,2025-12-31,3.99.01.01,ON,1.400000e-03,N,2025
164150,97.837.181/0001-47,2025-12-31,1,DEXCO S.A.,21091,DF Consolidado - Demonstração do Resultado,REAL,MIL,PENÚLTIMO,2024-01-01,2024-12-31,3.99.02,Lucro Diluído por Ação,0.000000e+00,N,2025
164151,97.837.181/0001-47,2025-12-31,1,DEXCO S.A.,21091,DF Consolidado - Demonstração do Resultado,REAL,MIL,ÚLTIMO,2025-01-01,2025-12-31,3.99.02,Lucro Diluído por Ação,0.000000e+00,N,2025
164152,97.837.181/0001-47,2025-12-31,1,DEXCO S.A.,21091,DF Consolidado - Demonstração do Resultado,REAL,MIL,PENÚLTIMO,2024-01-01,2024-12-31,3.99.02.01,ON,2.126000e-01,N,2025
164153,97.837.181/0001-47,2025-12-31,1,DEXCO S.A.,21091,DF Consolidado - Demonstração do Resultado,REAL,MIL,ÚLTIMO,2025-01-01,2025-12-31,3.99.02.01,ON,1.400000e-03,N,2025

In [3]:
caminho_tipo = "../data/raw/TIPO/cad_cia_aberta.csv"
df_tipo = pd.read_csv(caminho_tipo,sep=";",encoding="latin1")
df_tipo.columns.to_list() # procurando o Setor da empresa

['CNPJ_CIA',
 'DENOM_SOCIAL',
 'DENOM_COMERC',
 'DT_REG',
 'DT_CONST',
 'DT_CANCEL',
 'MOTIVO_CANCEL',
 'SIT',
 'DT_INI_SIT',
 'CD_CVM',
 'SETOR_ATIV',
 'TP_MERC',
 'CATEG_REG',
 'DT_INI_CATEG',
 'SIT_EMISSOR',
 'DT_INI_SIT_EMISSOR',
 'CONTROLE_ACIONARIO',
 'TP_ENDER',
 'LOGRADOURO',
 'COMPL',
 'BAIRRO',
 'MUN',
 'UF',
 'PAIS',
 'CEP',
 'DDD_TEL',
 'TEL',
 'DDD_FAX',
 'FAX',
 'EMAIL',
 'TP_RESP',
 'RESP',
 'DT_INI_RESP',
 'LOGRADOURO_RESP',
 'COMPL_RESP',
 'BAIRRO_RESP',
 'MUN_RESP',
 'UF_RESP',
 'PAIS_RESP',
 'CEP_RESP',
 'DDD_TEL_RESP',
 'TEL_RESP',
 'DDD_FAX_RESP',
 'FAX_RESP',
 'EMAIL_RESP',
 'CNPJ_AUDITOR',
 'AUDITOR']

In [4]:
df_tipo['SETOR_ATIV'].to_list() # Aqui eu to dando so uma olhada se realmente é o que eu pensei.

['Energia Elétrica',
 'Securitização de Recebíveis',
 'Emp. Adm. Part. - Energia Elétrica',
 'Emp. Adm. Part. - Sem Setor Principal',
 'Emp. Adm. Part. - Sem Setor Principal',
 'Emp. Adm. Participações',
 'Emp. Adm. Participações',
 'Máquinas, Equipamentos, Veículos e Peças',
 'Comércio (Atacado e Varejo)',
 'Máquinas, Equipamentos, Veículos e Peças',
 'Arrendamento Mercantil',
 'Gráficas e Editoras',
 'Emp. Adm. Part. - Const. Civil, Mat. Const. e Decoração',
 'Metalurgia e Siderurgia',
 'Metalurgia e Siderurgia',
 'Metalurgia e Siderurgia',
 'Metalurgia e Siderurgia',
 'Metalurgia e Siderurgia',
 'Metalurgia e Siderurgia',
 'Metalurgia e Siderurgia',
 'Petroquímicos e Borracha',
 'Securitização de Recebíveis',
 'Emp. Adm. Participações',
 'Agricultura (Açúcar, Álcool e Cana)',
 'Emp. Adm. Participações',
 'Petroquímicos e Borracha',
 'Petroquímicos e Borracha',
 'Farmacêutico e Higiene',
 'Saneamento, Serv. Água e Gás',
 'Máquinas, Equipamentos, Veículos e Peças',
 'Máquinas, Equipamentos, Veículos e Peças',
 'Serviços Diversos',
 'Emp. Adm. Part. - Energia Elétrica',
 'Emp. Adm. Part. - Energia Elétrica',
 'Emp. Adm. Part. - Energia Elétrica',
 'Energia Elétrica',
 'Energia Elétrica',
 'Securitização de Recebíveis',
 'Energia Elétrica',
 'Energia Elétrica',
 'Seguradoras e Corretoras',
 'Gráficas e Editoras',
 'Petróleo e Gás',
 'Construção Civil, Mat. Constr. e Decoração',
 'Máquinas, Equipamentos, Veículos e Peças',
 'Construção Civil, Mat. Constr. e Decoração',
 'Arrendamento Mercantil',
 'Agricultura (Açúcar, Álcool e Cana)',
 'Comércio (Atacado e Varejo)',
 'Agricultura (Açúcar, Álcool e Cana)',
 'Agricultura (Açúcar, Álcool e Cana)',
 'Saneamento, Serv. Água e Gás',
 'Saneamento, Serv. Água e Gás',
 'Saneamento, Serv. Água e Gás',
 'Saneamento, Serv. Água e Gás',
 'Saneamento, Serv. Água e Gás',
 'Saneamento, Serv. Água e Gás',
 'Saneamento, Serv. Água e Gás',
 'Saneamento, Serv. Água e Gás',
 'Emp. Adm. Part. - Serviços Transporte e Logística',
 'Outras Atividades Industriais',
 'Emp. Adm. Part. - Sem Setor Principal',
 'Emp. Adm. Part. - Telecomunicações',
 'Emp. Adm. Participações',
 'Emp. Adm. Participações',
 'Petroquímicos e Borracha',
 'Metalurgia e Siderurgia',
 'Metalurgia e Siderurgia',
 'Emp. Adm. Part. - Intermediação Financeira',
 'Têxtil e Vestuário',
 'Têxtil e Vestuário',
 'Telecomunicações',
 'Emp. Adm. Part. - Comércio (Atacado e Varejo)',
 'Emp. Adm. Participações',
 'Emp. Adm. Participações',
 'Emp. Adm. Part. - Agricultura (Açúcar, Álcool e Cana)',
 'Emp. Adm. Part. - Sem Setor Principal',
 'Serviços Médicos',
 'Comércio (Atacado e Varejo)',
 'Comércio (Atacado e Varejo)',
 'Emp. Adm. Part. - Sem Setor Principal',
 'Emp. Adm. Part. - Comércio (Atacado e Varejo)',
 'Emp. Adm. Part. - Comércio (Atacado e Varejo)',
 'Serviços Transporte e Logística',
 'Serviços Transporte e Logística',
 'Metalurgia e Siderurgia',
 'Emp. Adm. Part. - Comércio (Atacado e Varejo)',
 'Têxtil e Vestuário',
 'Têxtil e Vestuário',
 'Emp. Adm. Participações',
 'Emp. Adm. Part. - Seguradoras e Corretoras',
 'Construção Civil, Mat. Constr. e Decoração',
 'Máquinas, Equipamentos, Veículos e Peças',
 'Construção Civil, Mat. Constr. e Decoração',
 'Telecomunicações',
 'Securitização de Recebíveis',
 'Farmacêutico e Higiene',
 'Máquinas, Equipamentos, Veículos e Peças',
 'Metalurgia e Siderurgia',
 'Emp. Adm. Participações',
 'Emp. Adm. Part. - Energia Elétrica',
 'Metalurgia e Siderurgia',
 'Emp. Adm. Part. - Sem Setor Principal',
 'Bancos',
 'Metalurgia e Siderurgia',
 'Emp. Adm. Part. - Energia Elétrica',
 'Emp. Adm. Participações',
 'Têxtil e Vestuário',
 'Hospedagem e Turismo',
 'Telecomunicações',
 'Bebidas e Fumo',
 'Bebidas e Fumo',
 'Saneamento, Serv. Água e Gás',
 'Saneamento, Serv. Água e Gás',
 'Máquinas, Equipamentos, Veículos e Peças',
 'Arrendamento Mercantil',
 'Comércio (Atacado e Varejo)',
 'Comércio (Atacado e Varejo)',
 'Hospedagem e Turismo',
 'Telecomunicações',
 'Serviços Médicos',
 'Emp. Adm. Part. - Têxtil e Vestuário',
 'Energia Elétrica',
 'Emp. Adm. Part. - Energia Elétrica',
 'Emp. Adm. Part. - Comércio (Atacado e Varejo)',
 'Emp. Adm. Participações',
 'Máquinas, Equipamentos, Veículos e Peças',
 'Alimentos',
 'Emp. Adm. Part. - Sem Setor Principal',
 'Emp. Adm. Part. - Sem Setor Principal',
 'Energia Elétrica',
 'Emp. Adm. Part. - Educação',
 'Educação',
 'Construção Civil, Mat. Constr. e Decoração',
 'Metalurgia e Siderurgia',
 'Brinquedos e Lazer',
 'Petroquímicos e Borracha',
 'Securitização de Recebíveis',
 'Securitização de Recebíveis',
 'Papel e Celulose',
 'Petroquímicos e Borracha',
 'Alimentos',
 'Extração Mineral',
 'Emp. Adm. Part. - Intermediação Financeira',
 'Comércio (Atacado e Varejo)',
 'Emp. Adm. Part. - Sem Setor Principal',
 'Emp. Adm. Participações',
 'Metalurgia e Siderurgia',
 'Metalurgia e Siderurgia',
 'Metalurgia e Siderurgia',
 'Emp. Adm. Participações',
 'Emp. Adm. Participações',
 'Emp. Adm. Part. - Energia Elétrica',
 'Energia Elétrica',
 'Energia Elétrica',
 'Energia Elétrica',
 'Emp. Adm. Part. - Telecomunicações',
 'Emp. Adm. Part. - Telecomunicações',
 'Serviços Transporte e Logística',
 'Serviços Transporte e Logística',
 'Serviços Transporte e Logística',
 'Máquinas, Equipamentos, Veículos e Peças',
 'Outras Atividades Industriais',
 'Serviços Transporte e Logística',
 'Têxtil e Vestuário',
 'Emp. Adm. Part. - Energia Elétrica',
 'Outras Atividades Industriais',
 'Metalurgia e Siderurgia',
 'Emp. Adm. Part. - Energia Elétrica',
 'Emp. Adm. Part. - Comércio (Atacado e Varejo)',
 'Emp. Adm. Part. - Comércio (Atacado e Varejo)',
 'Emp. Adm. Part. - Serviços médicos',
 'Emp. Adm. Part. - Sem Setor Principal',
 'Telecomunicações',
 'Construção Civil, Mat. Constr. e Decoração',
 'Brinquedos e Lazer',
 'Petroquímicos e Borracha',
 'Farmacêutico e Higiene',
 'Educação',
 'Securitização de Recebíveis',
 'Emp. Adm. Part. - Extração Mineral',
 'Energia Elétrica',
 'Energia Elétrica',
 'Emp. Adm. Part. - Energia Elétrica',
 'Energia Elétrica',
 'Emp. Adm. Participações',
 'Emp. Adm. Part. - Serviços Transporte e Logística',
 'Máquinas, Equipamentos, Veículos e Peças',
 'Máquinas, Equipamentos, Veículos e Peças',
 'Serviços Transporte e Logística',
 'Emp. Adm. Part. - Comércio (Atacado e Varejo)',
 'Serviços Transporte e Logística',
 'Serviços Transporte e Logística',
 'Serviços Transporte e Logística',
 'Serviços Transporte e Logística',
 'Serviços Transporte e Logística',
 'Serviços Transporte e Logística',
 'Serviços Transporte e Logística',
 'Arrendamento Mercantil',
 'Emp. Adm. Participações',
 'Securitização de Recebíveis',
 'Securitização de Recebíveis',
 'Emp. Adm. Participações',
 'Energia Elétrica',
 'Energia Elétrica',
 'Emp. Adm. Part. - Energia Elétrica',
 'Energia Elétrica',
 'Energia Elétrica',
 'Petróleo e Gás',
 'Construção Civil, Mat. Constr. e Decoração',
 'Emp. Adm. Part. - Serviços Transporte e Logística',
 'Têxtil e Vestuário',
 'Securitização de Recebíveis',
 'Intermediação Financeira',
 'Bolsas de Valores/Mercadorias e Futuros',
 'Bolsas de Valores/Mercadorias e Futuros',
 'Papel e Celulose',
 'Energia Elétrica',
 'Agricultura (Açúcar, Álcool e Cana)',
 'Máquinas, Equipamentos, Veículos e Peças',
 'Hospedagem e Turismo',
 'Serviços Diversos',
 'Emp. Adm. Part. - Sem Setor Principal',
 'Crédito Imobiliário',
 'Bancos',
 'Emp. Adm. Part. - Intermediação Financeira',
 'Bancos',
 'Intermediação Financeira',
 'Bancos',
 'Bancos',
 'Bancos',
 'Bancos',
 'Bancos',
 'Bancos',
 'Bancos',
 'Bancos',
 'Bancos',
 'Bancos',
 'Bancos',
 'Bancos',
 'Bancos',
 'Bancos',
 'Bancos',
 'Bancos',
 'Bancos',
 'Bancos',
 'Bancos',
 'Bancos',
 'Bancos',
 'Bancos',
 'Bancos',
 'Bancos',
 'Bancos',
 'Bancos',
 'Bancos',
 'Bancos',
 'Bancos',
 'Bancos',
 'Bancos',
 'Bancos',
 'Bancos',
 'Bancos',
 'Bancos',
 'Bancos',
 'Bancos',
 'Bancos',
 'Bancos',
 'Bancos',
 'Bancos',
 'Bancos',
 'Arrendamento Mercantil',
 'Arrendamento Mercantil',
 'Bancos',
 'Bancos',
 'Bancos',
 'Bancos',
 'Bancos',
 'Bancos',
 'Bancos',
 'Bancos',
 'Bancos',
 'Bancos',
 'Bancos',
 'Bancos',
 'Bancos',
 'Bancos',
 'Bancos',
 'Bancos',
 'Bancos',
 'Bancos',
 nan,
 'Bancos',
 'Bancos',
 'Bancos',
 'Bancos',
 'Arrendamento Mercantil',
 'Arrendamento Mercantil',
 'Arrendamento Mercantil',
 'Bancos',
 'Arrendamento Mercantil',
 'Bancos',
 'Intermediação Financeira',
 'Bancos',
 'Bancos',
 nan,
 'Bancos',
 'Bancos',
 'Bancos',
 'Crédito Imobiliário',
 'Arrendamento Mercantil',
 'Serviços Transporte e Logística',
 'Bancos',
 'Bancos',
 'Têxtil e Vestuário',
 'Emp. Adm. Part. - Sem Setor Principal',
 'Máquinas, Equipamentos, Veículos e Peças',
 'Máquinas, Equipamentos, Veículos e Peças',
 'Securitização de Recebíveis',
 'Alimentos',
 'Securitização de Recebíveis',
 'Emp. Adm. Part. - Sem Setor Principal',
 'Petroquímicos e Borracha',
 'Embalagens',
 'Metalurgia e Siderurgia',
 'Emp. Adm. Part. - Seguradoras e Corretoras',
 'Arrendamento Mercantil',
 'Emp. Adm. Part. - Sem Setor Principal',
 'Arrendamento Mercantil',
 'Serviços Transporte e Logística',
 'Serviços Transporte e Logística',
 'Arrendamento Mercantil',
 'Emp. Adm. Part. - Serviços médicos',
 'Bancos',
 'Bancos',
 'Bancos',
 'Bancos',
 'Bancos',
 'Bancos',
 'Bancos',
 'Bancos',
 'Bancos',
 'Bancos',
 'Telecomunicações',
 'Bancos',
 'Emp. Adm. Part. - Crédito Imobiliário',
 'Energia Elétrica',
 'Emp. Adm. Part. - Sem Setor Principal',
 'Construção Civil, Mat. Constr. e Decoração',
 'Alimentos',
 'Comunicação e Informática',
 'Comunicação e Informática',
 'Petroquímicos e Borracha',
 'Emp. Adm. Part. - Sem Setor Principal',
 'Arrendamento Mercantil',
 'Comércio (Atacado e Varejo)',
 'Securitização de Recebíveis',
 'Emp. Adm. Part. - Crédito Imobiliário',
 'Construção Civil, Mat. Constr. e Decoração',
 'Arrendamento Mercantil',
 'Arrendamento Mercantil',
 'Bancos',
 'Emp. Adm. Part. - Sem Setor Principal',
 'Emp. Adm. Part. - Hospedagem e Turismo',
 'Securitização de Recebíveis',
 'Brinquedos e Lazer',
 'Farmacêutico e Higiene',
 'Emp. Adm. Part. - Educação',
 'Farmacêutico e Higiene',
 'Comunicação e Informática',
 'Agricultura (Açúcar, Álcool e Cana)',
 'Construção Civil, Mat. Constr. e Decoração',
 'Farmacêutico e Higiene',
 'Farmacêutico e Higiene',
 'Alimentos',
 'Hospedagem e Turismo',
 'Brinquedos e Lazer',
 'Securitização de Recebíveis',
 'Arrendamento Mercantil',
 'Arrendamento Mercantil',
 'Bancos',
 'Emp. Adm. Part. - Sem Setor Principal',
 'Alimentos',
 'Comunicação e Informática',
 'Arrendamento Mercantil',
 'Arrendamento Mercantil',
 'Bancos',
 'Têxtil e Vestuário',
 'Emp. Adm. Part. - Sem Setor Principal',
 'Bolsas de Valores/Mercadorias e Futuros',
 'Emp. Adm. Part. - Sem Setor Principal',
 'Farmacêutico e Higiene',
 'Emp. Adm. Part. - Comércio (Atacado e Varejo)',
 'Comércio (Atacado e Varejo)',
 'Serviços Diversos',
 'Emp. Adm. Part. - Energia Elétrica',
 'Construção Civil, Mat. Constr. e Decoração',
 'Construção Civil, Mat. Constr. e Decoração',
 'Petroquímicos e Borracha',
 'Alimentos',
 'Comércio (Atacado e Varejo)',
 'Máquinas, Equipamentos, Veículos e Peças',
 'Petroquímicos e Borracha',
 'Emp. Adm. Participações',
 'Comércio Exterior',
 'Têxtil e Vestuário',
 'Bolsas de Valores/Mercadorias e Futuros',
 'Emp. Adm. Part. - Sem Setor Principal',
 'Construção Civil, Mat. Constr. e Decoração',
 'Emp. Adm. Part. - Comércio (Atacado e Varejo)',
 'Emp. Adm. Part. - Comércio (Atacado e Varejo)',
 'Emp. Adm. Part. - Sem Setor Principal',
 'Emp. Adm. Part. - Sem Setor Principal',
 'Máquinas, Equipamentos, Veículos e Peças',
 'Arrendamento Mercantil',
 'Arrendamento Mercantil',
 'Arrendamento Mercantil',
 'Arrendamento Mercantil',
 'Arrendamento Mercantil',
 'Arrendamento Mercantil',
 'Hospedagem e Turismo',
 'Emp. Adm. Part. - Extração Mineral',
 'Emp. Adm. Part. - Intermediação Financeira',
 'Serviços Médicos',
 'Comércio (Atacado e Varejo)',
 'Metalurgia e Siderurgia',
 'Embalagens',
 'Construção Civil, Mat. Constr. e Decoração',
 'Máquinas, Equipamentos, Veículos e Peças',
 'Hospedagem e Turismo',
 'Construção Civil, Mat. Constr. e Decoração',
 'Energia Elétrica',
 'Hospedagem e Turismo',
 'Serviços Transporte e Logística',
 'Alimentos',
 'Alimentos',
 'Securitização de Recebíveis',
 'Securitização de Recebíveis',
 'Telecomunicações',
 'Emp. Adm. Part. - Telecomunicações',
 'Emp. Adm. Part. - Hospedagem e Turismo',
 'Agricultura (Açúcar, Álcool e Cana)',
 'Energia Elétrica',
 'Emp. Adm. Part. - Energia Elétrica',
 'Máquinas, Equipamentos, Veículos e Peças',
 'Extração Mineral',
 'Têxtil e Vestuário',
 'Construção Civil, Mat. Constr. e Decoração',
 'Petroquímicos e Borracha',
 'Emp. Adm. Participações',
 'Máquinas, Equipamentos, Veículos e Peças',
 'Hospedagem e Turismo',
 'Petróleo e Gás',
 'Petróleo e Gás',
 'Securitização de Recebíveis',
 'Emp. Adm. Part. - Comércio (Atacado e Varejo)',
 'Telecomunicações',
 'Emp. Adm. Part. - Crédito Imobiliário',
 'Bancos',
 'Bancos',
 'Emp. Adm. Part. - Bancos',
 'Securitização de Recebíveis',
 'Emp. Adm. Part. - Alimentos',
 'Comércio (Atacado e Varejo)',
 'Brinquedos e Lazer',
 'Emp. Adm. Part. - Telecomunicações',
 'Telecomunicações',
 'Emp. Adm. Part. - Saneamento, Serv. Água e Gás',
 'Emp. Adm. Part. - Saneamento, Serv. Água e Gás',
 'Emp. Adm. Part. - Const. Civil, Mat. Const. e Decoração',
 'Emp. Adm. Part. - Const. Civil, Mat. Const. e Decoração',
 'Securitização de Recebíveis',
 'Securitização de Recebíveis',
 'Securitização de Recebíveis',
 'Securitização de Recebíveis',
 'Securitização de Recebíveis',
 'Securitização de Recebíveis',
 'Comunicação e Informática',
 'Comunicação e Informática',
 'Emp. Adm. Part. - Telecomunicações',
 'Extração Mineral',
 'Construção Civil, Mat. Constr. e Decoração',
 'Emp. Adm. Part.-Bolsas de Valores/Mercadorias e Futuros',
 'Máquinas, Equipamentos, Veículos e Peças',
 nan,
 'Alimentos',
 'Emp. Adm. Part. - Energia Elétrica',
 'Telecomunicações',
 'Securitização de Recebíveis',
 'Comércio (Atacado e Varejo)',
 'Securitização de Recebíveis',
 'Arrendamento Mercantil',
 'Emp. Adm. Part. - Sem Setor Principal',
 'Emp. Adm. Part. - Sem Setor Principal',
 'Alimentos',
 'Têxtil e Vestuário',
 'Têxtil e Vestuário',
 'Serviços Diversos',
 'Alimentos',
 'Alimentos',
 'Petroquímicos e Borracha',
 'Petroquímicos e Borracha',
 'Arrendamento Mercantil',
 'Emp. Adm. Part. - Máqs., Equip., Veíc. e Peças',
 'Serviços Diversos',
 'Têxtil e Vestuário',
 'Emp. Adm. Part. - Hospedagem e Turismo',
 'Emp. Adm. Part. - Sem Setor Principal',
 'Energia Elétrica',
 'Têxtil e Vestuário',
 'Emp. Adm. Part. - Sem Setor Principal',
 'Emp. Adm. Part. - Metalurgia e Siderurgia',
 'Emp. Adm. Participações',
 'Alimentos',
 'Emp. Adm. Part. - Sem Setor Principal',
 'Emp. Adm. Participações',
 'Intermediação Financeira',
 'Seguradoras e Corretoras',
 'Emp. Adm. Part. - Seguradoras e Corretoras',
 'Agricultura (Açúcar, Álcool e Cana)',
 'Agricultura (Açúcar, Álcool e Cana)',
 'Têxtil e Vestuário',
 'Têxtil e Vestuário',
 'Emp. Adm. Participações',
 'Construção Civil, Mat. Constr. e Decoração',
 'Têxtil e Vestuário',
 'Alimentos',
 'Serviços Transporte e Logística',
 'Têxtil e Vestuário',
 'Máquinas, Equipamentos, Veículos e Peças',
 'Securitização de Recebíveis',
 'Emp. Adm. Part. - Comércio (Atacado e Varejo)',
 'Securitização de Recebíveis',
 'Emp. Adm. Part. - Telecomunicações',
 'Emp. Adm. Part. - Sem Setor Principal',
 'Metalurgia e Siderurgia',
 'Alimentos',
 'Alimentos',
 'Extração Mineral',
 'Emp. Adm. Part. - Sem Setor Principal',
 'Petroquímicos e Borracha',
 'Alimentos',
 'Comércio (Atacado e Varejo)',
 'Securitização de Recebíveis',
 nan,
 'Comércio (Atacado e Varejo)',
 'Comércio (Atacado e Varejo)',
 'Comércio (Atacado e Varejo)',
 'Emp. Adm. Participações',
 'Agricultura (Açúcar, Álcool e Cana)',
 'Alimentos',
 'Emp. Adm. Part. - Sem Setor Principal',
 'Construção Civil, Mat. Constr. e Decoração',
 'Construção Civil, Mat. Constr. e Decoração',
 'Emp. Adm. Part. - Petróleo e Gás',
 'Máquinas, Equipamentos, Veículos e Peças',
 'Máquinas, Equipamentos, Veículos e Peças',
 'Máquinas, Equipamentos, Veículos e Peças',
 'Arrendamento Mercantil',
 'Petroquímicos e Borracha',
 'Máquinas, Equipamentos, Veículos e Peças',
 'Emp. Adm. Part. - Extração Mineral',
 'Serviços Transporte e Logística',
 'Extração Mineral',
 'Construção Civil, Mat. Constr. e Decoração',
 'Construção Civil, Mat. Constr. e Decoração',
 'Emp. Adm. Part. - Educação',
 'Emp. Adm. Part. - Energia Elétrica',
 'Extração Mineral',
 'Máquinas, Equipamentos, Veículos e Peças',
 'Emp. Adm. Part. - Telecomunicações',
 'Máquinas, Equipamentos, Veículos e Peças',
 'Emp. Adm. Part. - Sem Setor Principal',
 'Energia Elétrica',
 'Energia Elétrica',
 'Telecomunicações',
 'Comércio (Atacado e Varejo)',
 'Emp. Adm. Part. - Extração Mineral',
 'Emp. Adm. Part. - Serviços Transporte e Logística',
 'Energia Elétrica',
 'Energia Elétrica',
 'Serviços Médicos',
 'Construção Civil, Mat. Constr. e Decoração',
 'Serviços Transporte e Logística',
 'Máquinas, Equipamentos, Veículos e Peças',
 'Construção Civil, Mat. Constr. e Decoração',
 'Extração Mineral',
 'Extração Mineral',
 'Extração Mineral',
 'Extração Mineral',
 'Securitização de Recebíveis',
 'Agricultura (Açúcar, Álcool e Cana)',
 'Energia Elétrica',
 'Energia Elétrica',
 'Construção Civil, Mat. Constr. e Decoração',
 'Telecomunicações',
 'Intermediação Financeira',
 'Intermediação Financeira',
 'Outras Atividades Industriais',
 'Petroquímicos e Borracha',
 'Alimentos',
 'Alimentos',
 'Arrendamento Mercantil',
 'Emp. Adm. Participações',
 'Energia Elétrica',
 'Alimentos',
 'Agricultura (Açúcar, Álcool e Cana)',
 'Alimentos',
 'Petroquímicos e Borracha',
 'Têxtil e Vestuário',
 'Bancos',
 'Emp. Adm. Participações',
 'Serviços Transporte e Logística',
 'Bancos',
 'Emp. Adm. Part. - Têxtil e Vestuário',
 'Emp. Adm. Participações',
 'Construção Civil, Mat. Constr. e Decoração',
 'Petroquímicos e Borracha',
 'Construção Civil, Mat. Constr. e Decoração',
 'Metalurgia e Siderurgia',
 'Alimentos',
 'Saneamento, Serv. Água e Gás',
 'Bebidas e Fumo',
 'Bebidas e Fumo',
 'Extração Mineral',
 'Extração Mineral',
 'Extração Mineral',
 'Extração Mineral',
 'Extração Mineral',
 'Máquinas, Equipamentos, Veículos e Peças',
 'Máquinas, Equipamentos, Veículos e Peças',
 'Construção Civil, Mat. Constr. e Decoração',
 'Saneamento, Serv. Água e Gás',
 'Energia Elétrica',
 'Emp. Adm. Part. - Sem Setor Principal',
 'Emp. Adm. Part. - Sem Setor Principal',
 'Petróleo e Gás',
 'Agricultura (Açúcar, Álcool e Cana)',
 'Agricultura (Açúcar, Álcool e Cana)',
 'Serviços Transporte e Logística',
 'Energia Elétrica',
 'Energia Elétrica',
 'Energia Elétrica',
 'Energia Elétrica',
 'Energia Elétrica',
 'Saneamento, Serv. Água e Gás',
 'Energia Elétrica',
 'Têxtil e Vestuário',
 'Têxtil e Vestuário',
 'Metalurgia e Siderurgia',
 'Metalurgia e Siderurgia',
 'Têxtil e Vestuário',
 'Metalurgia e Siderurgia',
 'Têxtil e Vestuário',
 'Têxtil e Vestuário',
 'Agricultura (Açúcar, Álcool e Cana)',
 'Metalurgia e Siderurgia',
 'Metalurgia e Siderurgia',
 'Alimentos',
 'Metalurgia e Siderurgia',
 'Têxtil e Vestuário',
 'Extração Mineral',
 'Alimentos',
 'Têxtil e Vestuário',
 'Alimentos',
 'Metalurgia e Siderurgia',
 'Têxtil e Vestuário',
 'Máquinas, Equipamentos, Veículos e Peças',
 'Têxtil e Vestuário',
 'Emp. Adm. Participações',
 'Emp. Adm. Participações',
 'Emp. Adm. Participações',
 'Emp. Adm. Participações',
 'Emp. Adm. Participações',
 'Alimentos',
 'Têxtil e Vestuário',
 'Construção Civil, Mat. Constr. e Decoração',
 'Bebidas e Fumo',
 'Extração Mineral',
 'Alimentos',
 'Pesca',
 'Petroquímicos e Borracha',
 'Têxtil e Vestuário',
 'Serviços Transporte e Logística',
 'Petroquímicos e Borracha',
 'Extração Mineral',
 'Emp. Adm. Participações',
 'Metalurgia e Siderurgia',
 'Energia Elétrica',
 'Petroquímicos e Borracha',
 'Serviços Diversos',
 'Petróleo e Gás',
 'Energia Elétrica',
 'Petroquímicos e Borracha',
 'Serviços Transporte e Logística',
 'Têxtil e Vestuário',
 'Securitização de Recebíveis',

In [5]:
cad_setor = df_tipo[["CD_CVM", "SETOR_ATIV"]]
# o cadastro tem empresa repetida (mesmo CD_CVM duas vezes) e o merge duplica
# as linhas do DRE. tira a duplicata antes de juntar pra não dobrar o lucro
print("CD_CVM repetidos no cadastro:", cad_setor["CD_CVM"].duplicated().sum())
cad_setor = cad_setor.drop_duplicates(subset=["CD_CVM"]).copy()
df_dre = df_dre.merge(cad_setor, on="CD_CVM", how="left")

print(df_dre["SETOR_ATIV"].isna().sum())  # confere quantas linhas ficaram sem setor (NaN)
df_dre.head()

CD_CVM repetidos no cadastro: 111
1822

,CNPJ_CIA,DT_REFER,VERSAO,DENOM_CIA,CD_CVM,GRUPO_DFP,MOEDA,ESCALA_MOEDA,ORDEM_EXERC,DT_INI_EXERC,DT_FIM_EXERC,CD_CONTA,DS_CONTA,VL_CONTA,ST_CONTA_FIXA,ANO_ARQUIVO,SETOR_ATIV
0,00.000.000/0001-91,2021-12-31,2,BCO BRASIL S.A.,1023,DF Consolidado - Demonstração do Resultado,REAL,MIL,PENÚLTIMO,2020-01-01,2020-12-31,3.01,Receitas de Intermediação Financeira,98659704.0,S,2021,Bancos
1,00.000.000/0001-91,2021-12-31,2,BCO BRASIL S.A.,1023,DF Consolidado - Demonstração do Resultado,REAL,MIL,ÚLTIMO,2021-01-01,2021-12-31,3.01,Receitas de Intermediação Financeira,125947217.0,S,2021,Bancos
2,00.000.000/0001-91,2021-12-31,2,BCO BRASIL S.A.,1023,DF Consolidado - Demonstração do Resultado,REAL,MIL,PENÚLTIMO,2020-01-01,2020-12-31,3.01.01,Receita de Juros,98659704.0,N,2021,Bancos
3,00.000.000/0001-91,2021-12-31,2,BCO BRASIL S.A.,1023,DF Consolidado - Demonstração do Resultado,REAL,MIL,ÚLTIMO,2021-01-01,2021-12-31,3.01.01,Receita de Juros,125947217.0,N,2021,Bancos
4,00.000.000/0001-91,2021-12-31,2,BCO BRASIL S.A.,1023,DF Consolidado - Demonstração do Resultado,REAL,MIL,PENÚLTIMO,2020-01-01,2020-12-31,3.02,Despesas de Intermediação Financeira,-43232120.0,S,2021,Bancos

In [6]:
df_dre.groupby("SETOR_ATIV")["CNPJ_CIA"].nunique().sort_values(ascending=False)

SETOR_ATIV
Construção Civil, Mat. Constr. e Decoração                 50
Comércio (Atacado e Varejo)                                44
Energia Elétrica                                           36
Serviços Transporte e Logística                            30
Emp. Adm. Part. - Energia Elétrica                         26
Máquinas, Equipamentos, Veículos e Peças                   23
Têxtil e Vestuário                                         21
Comunicação e Informática                                  21
Bancos                                                     20
Emp. Adm. Part. - Sem Setor Principal                      17
Serviços Médicos                                           16
Agricultura (Açúcar, Álcool e Cana)                        15
Emp. Adm. Part. - Serviços Transporte e Logística          14
Alimentos                                                  14
Metalurgia e Siderurgia                                    14
Telecomunicações                                           14
Emp. Adm. Part. - Const. Civil, Mat. Const. e Decoração    13
Saneamento, Serv. Água e Gás                               11
Emp. Adm. Part. - Comércio (Atacado e Varejo)               9
Educação                                                    9
Farmacêutico e Higiene                                      9
Petróleo e Gás                                              8
Emp. Adm. Part. - Telecomunicações                          6
Petroquímicos e Borracha                                    6
Emp. Adm. Part. - Petróleo e Gás                            5
Seguradoras e Corretoras                                    5
Emp. Adm. Part. - Educação                                  5
Brinquedos e Lazer                                          5
Emp. Adm. Part. - Alimentos                                 4
Emp. Adm. Part. - Intermediação Financeira                  4
Intermediação Financeira                                    4
Papel e Celulose                                            4
Emp. Adm. Part. - Metalurgia e Siderurgia                   4
Emp. Adm. Part. - Máqs., Equip., Veíc. e Peças              4
Emp. Adm. Part. - Comunicação e Informática                 4
Emp. Adm. Part. - Seguradoras e Corretoras                  4
Emp. Adm. Part. - Extração Mineral                          3
Emp. Adm. Part. - Serviços médicos                          3
Hospedagem e Turismo                                        3
Extração Mineral                                            3
Emp. Adm. Part. - Têxtil e Vestuário                        3
Emp. Adm. Part. - Agricultura (Açúcar, Álcool e Cana)       3
Bebidas e Fumo                                              2
Emp. Adm. Part. - Brinquedos e Lazer                        2
Emp. Adm. Part. - Saneamento, Serv. Água e Gás              2
Securitização de Recebíveis                                 2
Emp. Adm. Part. - Crédito Imobiliário                       2
Emp. Adm. Part. - Bancos                                    1
Embalagens                                                  1
Bolsas de Valores/Mercadorias e Futuros                     1
Emp. Adm. Part. - Papel e Celulose                          1
Name: CNPJ_CIA, dtype: int64

In [7]:
df_dre

,CNPJ_CIA,DT_REFER,VERSAO,DENOM_CIA,CD_CVM,GRUPO_DFP,MOEDA,ESCALA_MOEDA,ORDEM_EXERC,DT_INI_EXERC,DT_FIM_EXERC,CD_CONTA,DS_CONTA,VL_CONTA,ST_CONTA_FIXA,ANO_ARQUIVO,SETOR_ATIV
0,00.000.000/0001-91,2021-12-31,2,BCO BRASIL S.A.,1023,DF Consolidado - Demonstração do Resultado,REAL,MIL,PENÚLTIMO,2020-01-01,2020-12-31,3.01,Receitas de Intermediação Financeira,9.865970e+07,S,2021,Bancos
1,00.000.000/0001-91,2021-12-31,2,BCO BRASIL S.A.,1023,DF Consolidado - Demonstração do Resultado,REAL,MIL,ÚLTIMO,2021-01-01,2021-12-31,3.01,Receitas de Intermediação Financeira,1.259472e+08,S,2021,Bancos
2,00.000.000/0001-91,2021-12-31,2,BCO BRASIL S.A.,1023,DF Consolidado - Demonstração do Resultado,REAL,MIL,PENÚLTIMO,2020-01-01,2020-12-31,3.01.01,Receita de Juros,9.865970e+07,N,2021,Bancos
3,00.000.000/0001-91,2021-12-31,2,BCO BRASIL S.A.,1023,DF Consolidado - Demonstração do Resultado,REAL,MIL,ÚLTIMO,2021-01-01,2021-12-31,3.01.01,Receita de Juros,1.259472e+08,N,2021,Bancos
4,00.000.000/0001-91,2021-12-31,2,BCO BRASIL S.A.,1023,DF Consolidado - Demonstração do Resultado,REAL,MIL,PENÚLTIMO,2020-01-01,2020-12-31,3.02,Despesas de Intermediação Financeira,-4.323212e+07,S,2021,Bancos
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
164149,97.837.181/0001-47,2025-12-31,1,DEXCO S.A.,21091,DF Consolidado - Demonstração do Resultado,REAL,MIL,ÚLTIMO,2025-01-01,2025-12-31,3.99.01.01,ON,1.400000e-03,N,2025,"Construção Civil, Mat. Constr. e Decoração"
164150,97.837.181/0001-47,2025-12-31,1,DEXCO S.A.,21091,DF Consolidado - Demonstração do Resultado,REAL,MIL,PENÚLTIMO,2024-01-01,2024-12-31,3.99.02,Lucro Diluído por Ação,0.000000e+00,N,2025,"Construção Civil, Mat. Constr. e Decoração"
164151,97.837.181/0001-47,2025-12-31,1,DEXCO S.A.,21091,DF Consolidado - Demonstração do Resultado,REAL,MIL,ÚLTIMO,2025-01-01,2025-12-31,3.99.02,Lucro Diluído por Ação,0.000000e+00,N,2025,"Construção Civil, Mat. Constr. e Decoração"
164152,97.837.181/0001-47,2025-12-31,1,DEXCO S.A.,21091,DF Consolidado - Demonstração do Resultado,REAL,MIL,PENÚLTIMO,2024-01-01,2024-12-31,3.99.02.01,ON,2.126000e-01,N,2025,"Construção Civil, Mat. Constr. e Decoração"
164153,97.837.181/0001-47,2025-12-31,1,DEXCO S.A.,21091,DF Consolidado - Demonstração do Resultado,REAL,MIL,ÚLTIMO,2025-01-01,2025-12-31,3.99.02.01,ON,1.400000e-03,N,2025,"Construção Civil, Mat. Constr. e Decoração"

In [8]:
df_dre[df_dre["DS_CONTA"].str.contains("Lucro", case=False, na=False)]["CD_CONTA"].unique()

<ArrowStringArray>
[      '3.05',       '3.06',       '3.07',       '3.09',       '3.10',
       '3.11',       '3.99',    '3.99.01',    '3.99.02',       '3.08',
    '3.10.01',    '3.08.01', '3.04.05.04', '3.04.04.02',    '3.12.01',
       '3.13', '3.04.05.02', '3.04.02.03', '3.10.02.01', '3.04.05.01',
    '3.05.07', '3.10.01.01', '3.10.01.02', '3.04.06.01', '3.10.01.03']
Length: 25, dtype: str

In [9]:
df_dre[df_dre["DS_CONTA"].str.contains("Lucro", case=False, na=False)][["DS_CONTA", "CD_CONTA"]].drop_duplicates().sort_values("CD_CONTA")

                                                 DS_CONTA    CD_CONTA
19688             Participação dos colab. e adm. no lucro  3.04.02.03
30446     Programa de Participação dos Lucros e Resultado  3.04.02.03
12024                      Ganho na distribuição de lucro  3.04.04.02
20436   Lucro Proveniente da Alienação de Bens do Ativ...  3.04.04.02
30196              Participação dos Funcionários no Lucro  3.04.05.01
15578                Participação dos Empregados no Lucro  3.04.05.02
48840               Participações dos Empregados no Lucro  3.04.05.02
7386                  Participação de Empregados no Lucro  3.04.05.04
19766               Participação nos Lucros ou Resultados  3.04.05.04
120576  Participação nos lucros de coligadas, controla...  3.04.06.01
42             Resultado antes dos Tributos sobre o Lucro        3.05
694            Resultado Antes dos Tributos sobre o Lucro        3.05
47580               Participações nos Lucros - Empregados     3.05.07
44      Imposto de Renda e Contribuição Social sobre o...        3.06
50            Lucro ou Prejuízo das Operações Continuadas        3.07
230            Resultado Antes dos Tributos sobre o Lucro        3.07
232     Imposto de Renda e Contribuição Social sobre o...        3.08
706     Lucro/Prejuízo Líquido das Operações Descontin...     3.08.01
15254    Lucro/Prejuízo Líquido das Operações Desconti...     3.08.01
54      Lucro ou Prejuízo antes das Participações e Co...        3.09
710                 Lucro/Prejuízo Consolidado do Período        3.09
14202          Resultado Antes dos Tributos sobre o Lucro        3.09
56      Participações nos Lucros e Contribuições Estat...        3.10
14204   Imposto de Renda e Contribuição Social sobre o...        3.10
242     Lucro/Prejuízo Líquido das Operações Descontin...     3.10.01
159412  Participações nos Lucros e Contribuições Estat...     3.10.01
55898                       Incentivo lucro da exploração  3.10.01.01
58308       Lucro/Prejuízo Líquido da Dimensão de Techfin  3.10.01.01
58310      Lucro/Prejuízo Líquido da Operação de Hardware  3.10.01.02
156236  Lucro/Prejuízo Líquido da Operação Descontinua...  3.10.01.02
156238  Lucro/Prejuízo Líquido da Operação Descontinua...  3.10.01.03
26706   Lucro/Prejuizo Liquido das Operações Descontin...  3.10.02.01
79326   Participação nos lucros de empresas investidas...  3.10.02.01
58       Lucro ou Prejuízo Líquido Consolidado do Período        3.11
246                 Lucro/Prejuízo Consolidado do Período        3.11
14214   Lucro/Prejuízo Líquido das Operações Descontin...     3.12.01
14220               Lucro/Prejuízo Consolidado do Período        3.13
64                               Lucro por Ação (R$/Ação)        3.99
252                       Lucro por Ação - (Reais / Ação)        3.99
716                          Lucro por Ação - (R$ / Ação)        3.99
66                                  Lucro Básico por Ação     3.99.01
70                                 Lucro Diluído por Ação     3.99.02

In [10]:
df_lucro = df_dre[df_dre["CD_CONTA"] == "3.11"].copy()
df_lucro.head()

,CNPJ_CIA,DT_REFER,VERSAO,DENOM_CIA,CD_CVM,GRUPO_DFP,MOEDA,ESCALA_MOEDA,ORDEM_EXERC,DT_INI_EXERC,DT_FIM_EXERC,CD_CONTA,DS_CONTA,VL_CONTA,ST_CONTA_FIXA,ANO_ARQUIVO,SETOR_ATIV
58,00.000.000/0001-91,2021-12-31,2,BCO BRASIL S.A.,1023,DF Consolidado - Demonstração do Resultado,REAL,MIL,PENÚLTIMO,2020-01-01,2020-12-31,3.11,Lucro ou Prejuízo Líquido Consolidado do Período,13292883.0,S,2021,Bancos
59,00.000.000/0001-91,2021-12-31,2,BCO BRASIL S.A.,1023,DF Consolidado - Demonstração do Resultado,REAL,MIL,ÚLTIMO,2021-01-01,2021-12-31,3.11,Lucro ou Prejuízo Líquido Consolidado do Período,19722871.0,S,2021,Bancos
114,00.000.208/0001-00,2021-12-31,3,BRB BANCO DE BRASILIA S.A.,14206,DF Consolidado - Demonstração do Resultado,REAL,MIL,PENÚLTIMO,2020-12-01,2020-12-31,3.11,Lucro ou Prejuízo Líquido Consolidado do Período,349035.0,S,2021,Bancos
115,00.000.208/0001-00,2021-12-31,3,BRB BANCO DE BRASILIA S.A.,14206,DF Consolidado - Demonstração do Resultado,REAL,MIL,ÚLTIMO,2021-12-01,2021-12-31,3.11,Lucro ou Prejuízo Líquido Consolidado do Período,-407446.0,S,2021,Bancos
246,00.001.180/0001-26,2021-12-31,1,CENTRAIS ELET BRAS S.A. - ELETROBRAS,2437,DF Consolidado - Demonstração do Resultado,REAL,MIL,PENÚLTIMO,2020-01-01,2020-12-31,3.11,Lucro/Prejuízo Consolidado do Período,6387313.0,S,2021,Emp. Adm. Part. - Energia Elétrica

In [11]:
# antes de somar qualquer coisa, vou ver como o arquivo vem
# porque desconfiei que tem linha repetida pro mesmo ano
print(df_lucro["ORDEM_EXERC"].value_counts())
print("maior versão por empresa/ano:", df_lucro.groupby(["DENOM_CIA", "ANO_ARQUIVO"])["VERSAO"].max().max())
df_lucro[df_lucro["DENOM_CIA"] == "PETROLEO BRASILEIRO S.A. PETROBRAS"][["ANO_ARQUIVO", "DT_REFER", "VERSAO", "ORDEM_EXERC", "VL_CONTA"]].sort_values(["ANO_ARQUIVO", "VERSAO"]).head(12)

ORDEM_EXERC
ÚLTIMO       2318
PENÚLTIMO    2312
Name: count, dtype: int64
maior versão por empresa/ano: 6

        ANO_ARQUIVO    DT_REFER  VERSAO ORDEM_EXERC     VL_CONTA
19808          2021  2021-12-31       1   PENÚLTIMO    6246000.0
19809          2021  2021-12-31       1      ÚLTIMO  107264000.0
53138          2022  2022-12-31       1   PENÚLTIMO  107264000.0
53139          2022  2022-12-31       1      ÚLTIMO  189005000.0
86462          2023  2023-12-31       2   PENÚLTIMO  189005000.0
86463          2023  2023-12-31       2      ÚLTIMO  125166000.0
119902         2024  2024-12-31       1   PENÚLTIMO  125166000.0
119903         2024  2024-12-31       1      ÚLTIMO   37009000.0
150798         2025  2025-12-31       1   PENÚLTIMO   37009000.0
150799         2025  2025-12-31       1      ÚLTIMO  110605000.0

In [12]:
# achei o problema: o arquivo traz o ano atual (ÚLTIMO) e o ano anterior (PENÚLTIMO)
# como comparativo, e ainda tem empresa que reapresentou o balanço (mais de uma VERSAO)
# se somar tudo, o lucro sai duplicado. então:
# 1. fico só com o ÚLTIMO (o ano de verdade do arquivo)
# 2. fico só com a maior VERSAO de cada empresa/ano
df_lucro = df_lucro[df_lucro["ORDEM_EXERC"] == "ÚLTIMO"].copy()
df_lucro = df_lucro.sort_values("VERSAO").drop_duplicates(subset=["DENOM_CIA", "ANO_ARQUIVO"], keep="last").copy()
print("linhas depois do filtro:", len(df_lucro))
print("duplicados restantes (empresa/ano):", df_lucro.duplicated(subset=["DENOM_CIA", "ANO_ARQUIVO"]).sum())

linhas depois do filtro: 2289
duplicados restantes (empresa/ano): 0

In [13]:
# outra: nem todo mundo reporta em milhares. a Vivara e a Metisa, por exemplo,
# reportam em unidade. pra somar certo, padronizo tudo em milhares antes de agrupar
print(df_lucro["ESCALA_MOEDA"].value_counts())
escala = df_lucro["ESCALA_MOEDA"].astype(str).str.upper()
df_lucro["VL_CONTA_MIL"] = df_lucro["VL_CONTA"]
df_lucro.loc[~escala.str.contains("MIL", na=False), "VL_CONTA_MIL"] = df_lucro["VL_CONTA"] / 1000

ESCALA_MOEDA
MIL        2245
UNIDADE      44
Name: count, dtype: int64

In [14]:
df_lucro_ano = df_lucro.groupby(["DENOM_CIA", "SETOR_ATIV", "ANO_ARQUIVO"])["VL_CONTA_MIL"].sum().reset_index()
df_lucro_ano = df_lucro_ano.rename(columns={"VL_CONTA_MIL": "VL_CONTA"})
#quero ver o lucro por ano, por empresa e por setor.
df_lucro_ano = df_lucro_ano.sort_values(["ANO_ARQUIVO", "SETOR_ATIV", "VL_CONTA"], ascending=[True, True, False])
#quero fazer em ordem decrescente, do maior lucro para o menor lucro, por ano e por setor.
df_lucro_ano.head(20)

,DENOM_CIA,SETOR_ATIV,ANO_ARQUIVO,VL_CONTA
671,COSAN S.A.,"Agricultura (Açúcar, Álcool e Cana)",2021,6350776.0
1899,SLC AGRICOLA S.A.,"Agricultura (Açúcar, Álcool e Cana)",2021,1130759.0
1849,SAO MARTINHO S.A.,"Agricultura (Açúcar, Álcool e Cana)",2021,927124.0
1737,RAIZEN ENERGIA S.A.,"Agricultura (Açúcar, Álcool e Cana)",2021,593948.0
342,BRASILAGRO - CIA BRAS DE PROP AGRICOLAS,"Agricultura (Açúcar, Álcool e Cana)",2021,317646.0
461,CERRADINHO BIOENERGIA S.A.,"Agricultura (Açúcar, Álcool e Cana)",2021,264963.0
1235,JALLES MACHADO S.A.,"Agricultura (Açúcar, Álcool e Cana)",2021,170449.0
295,BIOSEV S.A.,"Agricultura (Açúcar, Álcool e Cana)",2021,163042.0
713,CTC - CENTRO DE TECNOLOGIA CANAVIEIRA S.A.,"Agricultura (Açúcar, Álcool e Cana)",2021,108398.0
2172,VITTIA S.A.,"Agricultura (Açúcar, Álcool e Cana)",2021,107740.0
2010,TERRA SANTA PROPRIEDADES AGRÍCOLAS S.A.,"Agricultura (Açúcar, Álcool e Cana)",2021,38024.0
1553,NUTRIPLANT INDUSTRIA E COMERCIO S.A.,"Agricultura (Açúcar, Álcool e Cana)",2021,6692.0
1675,POMIFRUTAS S/A EM RECUPERACAO JUDICIAL,"Agricultura (Açúcar, Álcool e Cana)",2021,288.0
1240,JBS S.A.,Alimentos,2021,20529653.0
1412,MARFRIG GLOBAL FOODS S.A.,Alimentos,2021,6646379.0
1457,MINERVA S.A.,Alimentos,2021,598879.0
1377,M.DIAS BRANCO S.A. IND COM DE ALIMENTOS,Alimentos,2021,504986.0
416,CAMIL ALIMENTOS S.A.,Alimentos,2021,462676.0
425,CARAMURU ALIMENTOS S.A.,Alimentos,2021,353867.0
1230,J. MACEDO S.A.,Alimentos,2021,134302.0

In [15]:
#Quero ver apenas os valores que não estão na escala de mil
df_dre[~df_dre["ESCALA_MOEDA"].str.contains("Mil")]

,CNPJ_CIA,DT_REFER,VERSAO,DENOM_CIA,CD_CVM,GRUPO_DFP,MOEDA,ESCALA_MOEDA,ORDEM_EXERC,DT_INI_EXERC,DT_FIM_EXERC,CD_CONTA,DS_CONTA,VL_CONTA,ST_CONTA_FIXA,ANO_ARQUIVO,SETOR_ATIV
0,00.000.000/0001-91,2021-12-31,2,BCO BRASIL S.A.,1023,DF Consolidado - Demonstração do Resultado,REAL,MIL,PENÚLTIMO,2020-01-01,2020-12-31,3.01,Receitas de Intermediação Financeira,9.865970e+07,S,2021,Bancos
1,00.000.000/0001-91,2021-12-31,2,BCO BRASIL S.A.,1023,DF Consolidado - Demonstração do Resultado,REAL,MIL,ÚLTIMO,2021-01-01,2021-12-31,3.01,Receitas de Intermediação Financeira,1.259472e+08,S,2021,Bancos
2,00.000.000/0001-91,2021-12-31,2,BCO BRASIL S.A.,1023,DF Consolidado - Demonstração do Resultado,REAL,MIL,PENÚLTIMO,2020-01-01,2020-12-31,3.01.01,Receita de Juros,9.865970e+07,N,2021,Bancos
3,00.000.000/0001-91,2021-12-31,2,BCO BRASIL S.A.,1023,DF Consolidado - Demonstração do Resultado,REAL,MIL,ÚLTIMO,2021-01-01,2021-12-31,3.01.01,Receita de Juros,1.259472e+08,N,2021,Bancos
4,00.000.000/0001-91,2021-12-31,2,BCO BRASIL S.A.,1023,DF Consolidado - Demonstração do Resultado,REAL,MIL,PENÚLTIMO,2020-01-01,2020-12-31,3.02,Despesas de Intermediação Financeira,-4.323212e+07,S,2021,Bancos
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
164149,97.837.181/0001-47,2025-12-31,1,DEXCO S.A.,21091,DF Consolidado - Demonstração do Resultado,REAL,MIL,ÚLTIMO,2025-01-01,2025-12-31,3.99.01.01,ON,1.400000e-03,N,2025,"Construção Civil, Mat. Constr. e Decoração"
164150,97.837.181/0001-47,2025-12-31,1,DEXCO S.A.,21091,DF Consolidado - Demonstração do Resultado,REAL,MIL,PENÚLTIMO,2024-01-01,2024-12-31,3.99.02,Lucro Diluído por Ação,0.000000e+00,N,2025,"Construção Civil, Mat. Constr. e Decoração"
164151,97.837.181/0001-47,2025-12-31,1,DEXCO S.A.,21091,DF Consolidado - Demonstração do Resultado,REAL,MIL,ÚLTIMO,2025-01-01,2025-12-31,3.99.02,Lucro Diluído por Ação,0.000000e+00,N,2025,"Construção Civil, Mat. Constr. e Decoração"
164152,97.837.181/0001-47,2025-12-31,1,DEXCO S.A.,21091,DF Consolidado - Demonstração do Resultado,REAL,MIL,PENÚLTIMO,2024-01-01,2024-12-31,3.99.02.01,ON,2.126000e-01,N,2025,"Construção Civil, Mat. Constr. e Decoração"
164153,97.837.181/0001-47,2025-12-31,1,DEXCO S.A.,21091,DF Consolidado - Demonstração do Resultado,REAL,MIL,ÚLTIMO,2025-01-01,2025-12-31,3.99.02.01,ON,1.400000e-03,N,2025,"Construção Civil, Mat. Constr. e Decoração"

In [16]:
pd.set_option("display.float_format", lambda x: f"{x:,.2f}")
df_lucro_ano["VL_CONTA_REAIS"] = df_lucro_ano["VL_CONTA"] * 1000
df_lucro_ano["VL_CONTA_BI"] = df_lucro_ano["VL_CONTA_REAIS"] / 1_000_000_000

In [17]:
df_lucro_ano

,DENOM_CIA,SETOR_ATIV,ANO_ARQUIVO,VL_CONTA,VL_CONTA_REAIS,VL_CONTA_BI
671,COSAN S.A.,"Agricultura (Açúcar, Álcool e Cana)",2021,"6,350,776.00","6,350,776,000.00",6.35
1899,SLC AGRICOLA S.A.,"Agricultura (Açúcar, Álcool e Cana)",2021,"1,130,759.00","1,130,759,000.00",1.13
1849,SAO MARTINHO S.A.,"Agricultura (Açúcar, Álcool e Cana)",2021,"927,124.00","927,124,000.00",0.93
1737,RAIZEN ENERGIA S.A.,"Agricultura (Açúcar, Álcool e Cana)",2021,"593,948.00","593,948,000.00",0.59
342,BRASILAGRO - CIA BRAS DE PROP AGRICOLAS,"Agricultura (Açúcar, Álcool e Cana)",2021,"317,646.00","317,646,000.00",0.32
...,...,...,...,...,...,...
508,CIA INDUSTRIAL SCHLOSSER S.A.,Têxtil e Vestuário,2025,-278.00,"-278,000.00",-0.00
944,FIACAO E TECELAGEM SAO JOSE SA EM RECUPERACAO ...,Têxtil e Vestuário,2025,"-7,728.00","-7,728,000.00",-0.01
1523,MUNDIAL S.A. - PRODUTOS DE CONSUMO,Têxtil e Vestuário,2025,"-21,970.00","-21,970,000.00",-0.02
2019,TEXTIL RENAUXVIEW S.A.,Têxtil e Vestuário,2025,"-57,092.00","-57,092,000.00",-0.06
1155,INBRANDS S.A.,Têxtil e Vestuário,2025,"-119,379.00","-119,379,000.00",-0.12

In [18]:
df_lucro_ano.sort_values("VL_CONTA_REAIS", ascending=False)

,DENOM_CIA,SETOR_ATIV,ANO_ARQUIVO,VL_CONTA,VL_CONTA_REAIS,VL_CONTA_BI
1649,PETROLEO BRASILEIRO S.A. PETROBRAS,Petróleo e Gás,2022,"189,005,000.00","189,005,000,000.00",189.00
1650,PETROLEO BRASILEIRO S.A. PETROBRAS,Petróleo e Gás,2023,"125,166,000.00","125,166,000,000.00",125.17
2130,VALE S.A.,Extração Mineral,2021,"121,343,000.00","121,343,000,000.00",121.34
1652,PETROLEO BRASILEIRO S.A. PETROBRAS,Petróleo e Gás,2025,"110,605,000.00","110,605,000,000.00",110.61
1648,PETROLEO BRASILEIRO S.A. PETROBRAS,Petróleo e Gás,2021,"107,264,000.00","107,264,000,000.00",107.26
...,...,...,...,...,...,...
353,BRASKEM S.A.,Petroquímicos e Borracha,2024,"-12,052,000.00","-12,052,000,000.00",-12.05
93,AMERICANAS S.A. - EM RECUPERAÇÃO JUDICIAL,Comércio (Atacado e Varejo),2022,"-12,911,538.00","-12,911,538,000.00",-12.91
2129,V. TAL - REDE NEUTRA DE TELECOMUNICAÇÕES S.A.,Telecomunicações,2025,"-13,855,499.00","-13,855,499,000.00",-13.86
1570,OI S.A. - EM RECUPERAÇÃO JUDICIAL,Telecomunicações,2022,"-19,265,934.00","-19,265,934,000.00",-19.27
1573,OI S.A. - EM RECUPERAÇÃO JUDICIAL,Telecomunicações,2025,"-36,368,915.00","-36,368,915,000.00",-36.37

In [19]:
df_lucro_ano.loc[df_lucro_ano.groupby("ANO_ARQUIVO")["VL_CONTA"].idxmax()]

,DENOM_CIA,SETOR_ATIV,ANO_ARQUIVO,VL_CONTA,VL_CONTA_REAIS,VL_CONTA_BI
2130,VALE S.A.,Extração Mineral,2021,"121,343,000.00","121,343,000,000.00",121.34
1649,PETROLEO BRASILEIRO S.A. PETROBRAS,Petróleo e Gás,2022,"189,005,000.00","189,005,000,000.00",189.00
1650,PETROLEO BRASILEIRO S.A. PETROBRAS,Petróleo e Gás,2023,"125,166,000.00","125,166,000,000.00",125.17
1651,PETROLEO BRASILEIRO S.A. PETROBRAS,Petróleo e Gás,2024,"37,009,000.00","37,009,000,000.00",37.01
1652,PETROLEO BRASILEIRO S.A. PETROBRAS,Petróleo e Gás,2025,"110,605,000.00","110,605,000,000.00",110.61

In [20]:
df_lucro_ano.to_csv("../data/processed/lucro_liquido_2021_2025.csv", index=False)